### PR TITLE
Remove database name from schema by default

### LINKED ISSUE #3578: Remove Database name from scaffold schema names by default
See https://github.com/linq2db/linq2db/discussions/3531#discussioncomment-2811562_

It makes no much sense to have database name information in schema for scaffolding, so we should hide it behind option.

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #3578

Database name schema information is unnecessary for most of users and just complicates interceptors implementation (especially when scaffold used against db with non-constant name)

### CODE REVIEW

**Review by sdanyliv — APPROVED** [review]

**Review by Shane32 — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]
I'd say update the other .tt file too, for the older t4 transformations. This is something I'm doing manually to my generated files from the older t4 in my projects currently.

**Comment by MaceWindu** [comment]
@viceroypenguin what do you mean? How database name affects T4?

**Comment by MaceWindu** [comment]
I see, Igor recently added table name to comment. Will remove db name

**Review by viceroypenguin — APPROVED** [review]

**Review by sdanyliv — APPROVED** [review]

**Pull request merged**
