### PR TITLE
Fix eager load detection (#2895)

### LINKED ISSUE #2895: Linq2db fails with "The method or operation is not implemented."
Hi! I encounter `NotImplementedException` from [here](https://github.com/linq2db/linq2db/blob/d9832b6e8dd60e4946e26c07f5e4ac241d167f11/Source/LinqToDB/Linq/Builder/SelectContext.cs#L876) I believe. 

Model is probably not in the simplest form to reproduce the error, but I tried to remove all the unnecessary details.

`The method or operation is not implemented.`
```
   at LinqToDB.Linq.Builder.SelectContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.PassThroughContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass55_0.<GetContext>b__0(IBuildContext ctx, Expression ex, Int32 l)
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction, Boolean throwOnError)
   at LinqToDB.Linq.Builder.SelectContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectManyBuilder.SelectManyContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectManyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectManyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.EagerLoading.<>c__DisplayClass41_0`2.<RegisterPreambles>b__0(IDataContext dc, Expression expr, Object[] ps)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass187_0`1.<RegisterPreamble>b__0(IDataContext dc, Expression e, Object[] ps)
   at LinqToDB.Linq.Query.InitPreambles(IDataContext dc, Expression rootExpression, Object[] ps)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Repro.Program.Main(String[] args) in D:\dev\Repro\Program.cs:line 22
```

### Steps to reproduce
Here is the problematic query
```c#
var connectionString = "Data Source=.;Initial Catalog=Repro;Integrated Security=True; MultipleActiveResultSets=True";

var builder = new LinqToDbConnectionOptionsBuilder();
builder.UseSqlServer(connectionString);

var dbContext = new DbContext(builder.Build());

var failing = dbContext.Requests
	.Select(r => new
	{
		DocumentName = r.User.Admin.EmailAdminAssociations
			.Select(ea => ea.Email.InternalEmail)
			.Select(ie => new
			{
				Names = ie.Email.EmailAttachmentAssociations
					.SelectMany(eba => eba.Attachment.Documents.Select(aa => aa.Name)),
			})
			.FirstOrDefault(),
	})
	.ToArray();
```

Data connection type looks this way
```c#
public class DbContext : DataConnection
{
	public DbContext(LinqToDbConnectionOptions options) : base(options: options) { }

	public ITable<Request> Requests => GetTable<Request>();
	public ITable<InternalEmail> InternalEmails => GetTable<InternalEmail>();
	public ITable<User> Users => GetTable<User>();
	public ITable<Admin> Admins => GetTable<Admin>();
	public ITable<EmailAdminAssociation> EmailAdminAssociations => GetTable<EmailAdminAssociation>();
	public ITable<Email> Emails => GetTable<Email>();
	public ITable<EmailAttachmentAssociation> EmailAttachmentAssociations => GetTable<EmailAttachmentAssociation>();
	public ITable<Attachment> Attachments => GetTable<Attachment>();
	public ITable<Document> Documents => GetTable<Document>();
}
```

And here is the model
```c#
[Table]
public class InternalEmail 
{
	[PrimaryKey, Column]
	public int Id { get; set; }

	[Column]
	public int? RequestId { get; set; }

	[Column]
	public int? UserId { get; set; }

	[Association(ThisKey = nameof(RequestId), OtherKey = nameof(Repro.Request.Id))]
	public virtual Request Request { get; set; }

	[Association(ThisKey = nameof(UserId), OtherKey = nameof(Repro.User.Id))]
	public virtual User User { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(Repro.Email.Id))]
	public virtual Email Email { get; set; }
}

[Table]
public class Request
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Column]
	public int UserId { get; set; }

	[Association(ThisKey = nameof(UserId), OtherKey = nameof(Repro.User.Id))]
	public virtual User User { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(InternalEmail.Id))]
	public virtual ICollection<InternalEmail> InternalEmails { get; set; }
}

[Table]
public class User
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(Repro.Admin.Id))]
	public virtual Admin Admin { get; set; }
}

[Table]
public class Admin
{
	[PrimaryKey, Column]
	public int Id { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(EmailAdminAssociation.AdminId))]
	public virtual ICollection<EmailAdminAssociation> EmailAdminAssociations { get; set; }
}

[Table]
public class EmailAdminAssociation
{
	[PrimaryKey(1)]
	[Column]
	public int EmailId { get; set; }

	[PrimaryKey(2)]
	[Column]
	public int AdminId { get; set; }

	[Association(ThisKey = nameof(EmailId), OtherKey = nameof(Repro.Email.Id))]
	public virtual Email Email { get; set; }

	[Association(ThisKey = nameof(AdminId), OtherKey = nameof(Repro.Admin.Id))]
	public virtual Admin Admin { get; set; }
}

[Table]
public class Email
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(Repro.InternalEmail.Id))]
	public virtual InternalEmail InternalEmail { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(EmailAttachmentAssociation.EmailId))]
	public virtual ICollection<EmailAttachmentAssociation> EmailAttachmentAssociations { get; set; }
}

[Table]
public class EmailAttachmentAssociation
{
	[PrimaryKey(1)]
	[Column]
	public int EmailId { get; set; }

	[PrimaryKey(2)]
	[Column]
	public int AttachmentId { get; set; }

	[Association(ThisKey = nameof(AttachmentId), OtherKey = nameof(Repro.Attachment.Id))]
	public virtual Attachment Attachment { get; set; }

	[Association(ThisKey = nameof(EmailId), OtherKey = nameof(Repro.Email.Id))]
	public virtual Email Email { get; set; }
}

[Table]
public class Attachment
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(Document.AttachmentId))]
	public virtual ICollection<Document> Documents { get; set; }
}

[Table]
public class Document
{
	[PrimaryKey(1)]
	[Column]
	public int AttachmentId { get; set; }

	[PrimaryKey(2)]
	[Column]
	public int Position { get; set; }

	[Column]
	public string Name { get; set; }
}
```

Whole solution to reproduce the issue is here
[Repro.zip](https://github.com/linq2db/linq2db/files/6149213/Repro.zip)

### Environment details
linq2db version: 3.2.3
Database Server: MS SQL Server 14.0.1000
Database Provider: Default Sql Server provider, which is "SqlServer", I believe
Operating system: Windows 10.0.18363 
.NET Framework: 4.8

### LINKED ISSUE #3161: Nested subquery does not execute
Executing a outer apply within another outer apply can fail in recent versions of linq2db:

```cs
var ret = db.GetTable<Table1>()
	.Select(t1 => new
	{
		//retrieve Table1.Name1
		Name1 = t1.Name1,
		Value1 = db.GetTable<Table2>()
			.Where(x => x.ParentId2 == t1.Id1)
			.Select(t2 => new
			{
                                //retrieve Table2.Name2 via outer apply
				Name2 = t2.Name2,
				Value2 = db.GetTable<Table3>()
					.Where(x => x.ParentId3 == t2.Id2)
					.Select(t3 => new
					{
                                                //retrieve Table3.Name3 and Table3.Id3 via outer apply
						Name3 = t3.Name3,
						Value3 = t3.Id3
					})
					.FirstOrDefault()
			})
			.FirstOrDefault()
	})
	.ToList();
```

While a single cross apply between Table1 and Table2 works fine, adding the cross apply for Table3 breaks the sample.  For instance, the below code works fine:

```cs
var ret = db.GetTable<Table1>()
	.Select(t1 => new
	{
                //retrieve Table1.Name1
		Name1 = t1.Name1,
		Value1 = db.GetTable<Table2>()
			.Where(x => x.ParentId2 == t1.Id1)
			.Select(t2 => new
			{
                                //retrieve Table2.Name2 and Table2.Id2 via outer apply
				Name2 = t2.Name2,
				Value2 = t2.Id2
			})
			.FirstOrDefault()
	})
	.ToList();
```

The exception is the following:

```
System.Data.SqlClient.SqlException : Only one expression can be specified in the select list
when the subquery is not introduced with EXISTS.
```

The faulty code is producing invalid SQL as follows:

```sql
DECLARE @take Int -- Int32
SET     @take = 1
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT
	[t1_1].[NAME1],
	[t2].[Name2],
	[t2].[Name3],
	[t2].[Value3]
FROM
	[TABLE1] [t1_1]
		OUTER APPLY (
			SELECT TOP (@take)
				[x_1].[NAME2] as [Name2],
				/**** This portion of the SQL statment should not be 
				      present, and the query would work without it *****/
				(
					SELECT TOP (@take_1)
						[x].[NAME3],
						[x].[ID3]
					FROM
						[TABLE3] [x]
					WHERE
						[x].[PARENTID3] = [x_1].[ID2]
				) as [Value2],
				/*************************************************/
				[t1].[Name3],
				[t1].[Value3]
			FROM
				[TABLE2] [x_1]
					OUTER APPLY (
						SELECT TOP (@take_1)
							[x].[NAME3] as [Name3],
							[x].[ID3] as [Value3]
						FROM
							[TABLE3] [x]
						WHERE
							[x].[PARENTID3] = [x_1].[ID2]
					) [t1]
			WHERE
				[x_1].[PARENTID2] = [t1_1].[ID1]
		) [t2]
```

See `Tests/Linq/UserTests/Issue3161Tests.cs` for test marked with `[ActiveIssue]`.  Note that `Issue3160Tests.NestedDictionaryTest3CrossApply` works fine and is set up relatively similar, with a nested outer apply.

### Environment details
linq2db version: 3.3.0 - 4.0 beta
Database Server: SQL Server
Operating system: Windows 10
.NET Framework: .NET 5

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #2895
Fix #3161

- restored old fix and adjusted detection logic
- also fixed (?) lambda convert code

### CODE REVIEW

**Comment by Shane32** [comment]
@MaceWindu :+1: Excellent that the patch here has restored the old fix without breaking other queries.  However, I would like to point out that this does not correctly solve #3161 - while it is good that the query executes, it does so incorrectly and executes two queries instead of one.

If we look at the baselines, we can see what it is executing:

```sql
DECLARE @take Int -- Int32
SET     @take = 1

SELECT
	[t1_1].[ID1],  -- notice here it is pulling the id from table1, not the name
	[detail].[NAME2],
	[t1].[Name3],
	[t1].[Value3]
FROM
	[TABLE1] [t1_1]
		INNER JOIN [TABLE2] [detail] ON [detail].[PARENTID2] = [t1_1].[ID1]
		OUTER APPLY (
			SELECT TOP (@take)
				[_x].[NAME3] as [Name3],
				[_x].[ID3] as [Value3]
			FROM
				[TABLE3] [_x]
			WHERE
				[_x].[PARENTID3] = [detail].[ID2]
		) [t1]

BeforeExecute
-- SqlServer.2008

SELECT
	[t1].[NAME1],
	[t1].[ID1]
FROM
	[TABLE1] [t1]
```

But it should be something like this:

```sql
DECLARE @take Int -- Int32
SET     @take = 1

SELECT
        [t1_1].[NAME1],   -- it should pull the name and not the id from table1
	[detail].[NAME2],
	[t1].[Name3],
	[t1].[Value3]
FROM
	[TABLE1] [t1_1]
		INNER JOIN [TABLE2] [detail] ON [detail].[PARENTID2] = [t1_1].[ID1]
		OUTER APPLY (
			SELECT TOP (@take)
				[_x].[NAME3] as [Name3],
				[_x].[ID3] as [Value3]
			FROM
				[TABLE3] [_x]
			WHERE
				[_x].[PARENTID3] = [detail].[ID2]
		) [t1]
```

We can of course merge this and I can open a new issue, or update the existing issue.  But essentially, this query should not be detected as a 'eager loading query' at all, and should execute as an inner join with a cross apply, or a cross apply with another cross apply.

**Comment by MaceWindu** [comment]
Well, in that case test should be updated to fail

**Comment by Shane32** [comment]
> Well, in that case test should be updated to fail

I agree.  Is there a way to have the test fail if it executes multiple queries?

**Comment by MaceWindu** [comment]
hmm, probably check LastSQL for expected clauses...

**Comment by Shane32** [comment]
Perhaps validate that `"\nSELECT"` (or `Environment.NewLine + "SELECT"`) only occurs once?

**Comment by Shane32** [comment]
How about this, added to the end of `Issue3161Tests.CrossApplyTwice`?

```cs
// validate that the prior executed as a single query, not two distinct queries
// LastQuery will only return a single query, so if it was split into two queries, not all name fields would be present
var lastQuery = ((DataConnection)db).LastQuery;
Assert.That(lastQuery, Contains.Substring("NAME1"));
Assert.That(lastQuery, Contains.Substring("NAME2"));
Assert.That(lastQuery, Contains.Substring("NAME3"));
```

**Comment by MaceWindu** [comment]
@Shane32 open new issue for later. It will require @sdanyliv attention to fix.

**Comment by MaceWindu** [comment]
I've tried to use additional check using `IsMultipleQuery` - it produce single query, but it is not even valid sql
```sql
SELECT
	[t1_1].[NAME1],
	[t2].[Name2],
	[t2].[Name3],
	[t2].[Value3]
FROM
	[TABLE1] [t1_1]
		OUTER APPLY (
			SELECT TOP (@take)
				[x_1].[NAME2] as [Name2],
				(
					SELECT TOP (@take_1)
						[x].[NAME3],
						[x].[ID3]
					FROM
						[TABLE3] [x]
					WHERE
						[x].[PARENTID3] = [x_1].[ID2]
				) as [Value2],
				[t1].[Name3],
				[t1].[Value3]
			FROM
				[TABLE2] [x_1]
					OUTER APPLY (
						SELECT TOP (@take_1)
							[x].[NAME3] as [Name3],
							[x].[ID3] as [Value3]
						FROM
							[TABLE3] [x]
						WHERE
							[x].[PARENTID3] = [x_1].[ID2]
					) [t1]
			WHERE
				[x_1].[PARENTID2] = [t1_1].[ID1]
		) [t2]
``

**Comment by Shane32** [comment]
So for now we will not reconfigure the test to fail?

**Review by sdanyliv — APPROVED** [review]

**Review by Shane32 — APPROVED** [review]

**Comment by Shane32** [comment]
> @Shane32 open new issue for later. It will require @sdanyliv attention to fix.

done - #3462

**Pull request merged**
