### PR TITLE
Release 2.9.7

### PR DESCRIPTION
**Pull request by MaceWindu**
- run tests
    - [x] netfx
    - [x] netcore1
    - [x] netcore2

@linq2db/testers we plan to release on thursday (5/03)

[release notes](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#release-297)

### CODE REVIEW

**Comment by detoxhby** [comment]
Will try to test it on wednesday.

Btw, there is still no myget feed for v2 branch, can we fix it somehow? Really makes the testing process unnecessarily problematic.

**Comment by MaceWindu** [comment]
completely forgot about myget issue. will look into it

**Comment by MaceWindu** [comment]
@detoxhby we identified issue with myget. I will publish new version later today

**Comment by detoxhby** [comment]
⚠️ @MaceWindu @sdanyliv 

Done testing the new **2.9.7-rc4663** version and there were several `Expression.Bind` query construction error cases which were working previously without any issue.

It is a mistake from app side in terms of existing AutoMapper mapping definitions did not ignore class members explicitly (*or just invalid new expression were used in repositories, doesn't matter*), but still a huge problem as the exception is not handled in `ExpressionBuilder.TransformExpression()` ... `case ExpressionType.MemberInit` part, so the user has absolutely no information what member is the problem because of the generic `System.Linq.Expressions.Expression.Bind(System.Reflection.MemberInfo, System.Linq.Expressions.Expression) - System.ArgumentException: 'Argument types do not match.'`. The problem escalates when the projection uses nested objects, as we would need the full property path to the nested member to at least be able to identify the case (plus to make it worse, the exception is swallowed in Query<T>.CreateQuery() call).

The main idea of detecting invalid projection members is super useful, but current implementation just broke working application code without any clue on what should be fixed. Common developers without deeper technical knowledge in expressions or in general would simply not able to determine the causes.

I recommend delaying the release if couldn't fix&test this issue properly as it would affect lot of projects.

**Comment by sdanyliv** [comment]
@detoxhby, i know which PR may cause problem. Could you please show me failing query?

**Comment by sdanyliv** [comment]
Also it would be better to send PR which may help to decorate exception.

**Comment by detoxhby** [comment]
Alright, tracked the problem even further, and it could be an edge case.

 - entity class has a property `public Type StateType { get; set; }` which is annotated with `[NotColumn]` attribute
 - the destination DTO class also has this property
 - AutoMapper's projection enforces the selection of this column during the query (this is the problem I talked about previously as "app mistake", it sould be explicitly excluded)

(*questionable*) should exclude the prop during query building
...or...
(*also questionable*) should include an edge case for `Type` typed members handling

I cannot generate nor provide full query with proper entity classes currently (maybe tomorrow), but here is the problematic expression which included the `StateType` property in the nested projection:
```
.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.Where(
        .Constant<LinqToDB.Linq.Table`1[Core.Entities.ProjectWorkflowTransition]>(Table([ProjectWorkflowTransitions])),
        '(.Lambda #Lambda1<System.Func`2[Core.Entities.ProjectWorkflowTransition,System.Boolean]>)),
    '(.Lambda #Lambda2<System.Func`2[Core.Entities.ProjectWorkflowTransition,BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflowTransition]>))

.Lambda #Lambda1<System.Func`2[Core.Entities.ProjectWorkflowTransition,System.Boolean]>(Core.Entities.ProjectWorkflowTransition $x)
{
    $x.ProjectWorkflowId == .Constant<DataAccess.Implementations.ProjectWorkflowTransitionRepository+<>c__DisplayClass5_0>(DataAccess.Implementations.ProjectWorkflowTransitionRepository+<>c__DisplayClass5_0).workflowId
}

.Lambda #Lambda2<System.Func`2[Core.Entities.ProjectWorkflowTransition,BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflowTransition]>(Core.Entities.ProjectWorkflowTransition $dtoProjectWorkflowTransition)
{
    .New BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflowTransition(){
        DestinationStateId = $dtoProjectWorkflowTransition.OutputStateId,
        Id = $dtoProjectWorkflowTransition.Id,
        Name = $dtoProjectWorkflowTransition.Name,
        ProjectWorkflow = .If ($dtoProjectWorkflowTransition.ProjectWorkflow == null) {
            null
        } .Else {
            .New BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflow(){
                CurrentState = .If (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState == null) {
                    null
                } .Else {
                    .New BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflowState(){
                        AssigneePrincipalId = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).AssigneePrincipalId,
                        AssigneePrincipalType = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).AssigneePrincipalType,
                        Attributes = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).Attributes,
                        Description = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).Description,
                        EnterDate = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).EnterDate,
                        EstimatedTimeToComplete = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).EstimatedTimeToComplete,
                        ETID = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).ETID,
                        Id = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).Id,
                        IsValidationRequired = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).IsValidationRequired,
                        LeaveDate = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).LeaveDate,
                        Name = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).Name,
                        ScopeOfFiles = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).ScopeOfFiles,
                        SimultaneousEmployeeCount = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).SimultaneousEmployeeCount,
               -------> StateType = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).StateType,
                        TypeId = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).TypeId,
                        ValidatorPrincipalId = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).ValidatorPrincipalId,
                        ValidatorPrincipalType = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).ValidatorPrincipalType,
                        WorkflowId = (($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentState).ProjectWorkflowId
                    }
                },
                CurrentStateId = ($dtoProjectWorkflowTransition.ProjectWorkflow).CurrentStateId,
                Description = ($dtoProjectWorkflowTransition.ProjectWorkflow).Description,
                Id = ($dtoProjectWorkflowTransition.ProjectWorkflow).Id,
                IsDeleted = ($dtoProjectWorkflowTransition.ProjectWorkflow).IsDeleted,
                Name = ($dtoProjectWorkflowTransition.ProjectWorkflow).Name,
                ParentId = ($dtoProjectWorkflowTransition.ProjectWorkflow).ParentId,
                ParentWorkflowState = .If (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState == null) {
                    null
                } .Else {
                    .New BusinessLogic.Workflows.ProjectWorkflow.Models.ProjectWorkflowState(){
                        AssigneePrincipalId = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).AssigneePrincipalId,
                        AssigneePrincipalType = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).AssigneePrincipalType,
                        Attributes = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).Attributes,
                        Description = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).Description,
                        EnterDate = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).EnterDate,
                        EstimatedTimeToComplete = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).EstimatedTimeToComplete,
                        ETID = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).ETID,
                        Id = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).Id,
                        IsValidationRequired = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).IsValidationRequired,
                        LeaveDate = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).LeaveDate,
                        Name = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).Name,
                        ScopeOfFiles = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).ScopeOfFiles,
                        SimultaneousEmployeeCount = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).SimultaneousEmployeeCount,
              ------->  StateType = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).StateType,
                        TypeId = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).TypeId,
                        ValidatorPrincipalId = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).ValidatorPrincipalId,
                        ValidatorPrincipalType = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).ValidatorPrincipalType,
                        WorkflowId = (($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowState).ProjectWorkflowId
                    }
                },
                ParentWorkflowStateId = ($dtoProjectWorkflowTransition.ProjectWorkflow).ParentWorkflowStateId,
                Project = ($dtoProjectWorkflowTransition.ProjectWorkflow).Project,
                ProjectId = ($dtoProjectWorkflowTransition.ProjectWorkflow).ProjectId,
                ProjectWorkflowTemplateGroup = ($dtoProjectWorkflowTransition.ProjectWorkflow).ProjectWorkflowTemplateGroup,
                ProjectWorkflowTemplateGroupId = ($dtoProjectWorkflowTransition.ProjectWorkflow).ProjectWorkflowTemplateGroupId
            }
        },
        SourceStateId = $dtoProjectWorkflowTransition.InputStateId,
        WorkflowId = $dtoProjectWorkflowTransition.ProjectWorkflowId
    }
}
```

If I could find some time tomorrow, I will do a diff with previous version to find out what is the main disparity.

**Comment by sdanyliv** [comment]
@detoxhby, use this Extension to visualise ExpressionTree https://github.com/agileobjects/ReadableExpressions 
and post it again or correct previous one.

I thought i have fixed this problem with NotMapped column. For now it should be initialized by 'default' value, because it is not mapped to database.

I will try to create complex scenario as in your case. I do not think it is huge problem to fix such situation, but i need your support.

**Comment by detoxhby** [comment]
@sdanyliv I thought the raw expression would help better in a simple query, but sure, I've included the formatted expression (ℹ️ keep in mind, that this is an AutoMapper projection)

NOTE: I won't be available till tomorrow, cannot provide further data today

```csharp
Table<ProjectWorkflowTransition>.Where<ProjectWorkflowTransition>(x => x.ProjectWorkflowId == workflowId).Select<ProjectWorkflowTransition, ProjectWorkflowTransition>(
    dtoProjectWorkflowTransition => new ProjectWorkflowTransition
    {
        DestinationStateId = dtoProjectWorkflowTransition.OutputStateId,
        Id = dtoProjectWorkflowTransition.Id,
        Name = dtoProjectWorkflowTransition.Name,
        ProjectWorkflow = (dtoProjectWorkflowTransition.ProjectWorkflow == null)
            ? null
            : new ProjectWorkflow
            {
                CurrentState = (dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState == null)
                    ? null
                    : new ProjectWorkflowState
                    {
                        AssigneePrincipalId = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.AssigneePrincipalId,
                        AssigneePrincipalType = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.AssigneePrincipalType,
                        Attributes = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.Attributes,
                        Description = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.Description,
                        EnterDate = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.EnterDate,
                        EstimatedTimeToComplete = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.EstimatedTimeToComplete,
                        ETID = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.ETID,
                        Id = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.Id,
                        IsValidationRequired = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.IsValidationRequired,
                        LeaveDate = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.LeaveDate,
                        Name = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.Name,
                        ScopeOfFiles = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.ScopeOfFiles,
                        SimultaneousEmployeeCount = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.SimultaneousEmployeeCount,
                        StateType = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.StateType,
                        TypeId = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.TypeId,
                        ValidatorPrincipalId = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.ValidatorPrincipalId,
                        ValidatorPrincipalType = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.ValidatorPrincipalType,
                        WorkflowId = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentState.ProjectWorkflowId
                    },
                CurrentStateId = dtoProjectWorkflowTransition.ProjectWorkflow.CurrentStateId,
                Description = dtoProjectWorkflowTransition.ProjectWorkflow.Description,
                Id = dtoProjectWorkflowTransition.ProjectWorkflow.Id,
                IsDeleted = dtoProjectWorkflowTransition.ProjectWorkflow.IsDeleted,
                Name = dtoProjectWorkflowTransition.ProjectWorkflow.Name,
                ParentId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentId,
                ParentWorkflowState = (dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState == null)
                    ? null
                    : new ProjectWorkflowState
                    {
                        AssigneePrincipalId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.AssigneePrincipalId,
                        AssigneePrincipalType = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.AssigneePrincipalType,
                        Attributes = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.Attributes,
                        Description = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.Description,
                        EnterDate = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.EnterDate,
                        EstimatedTimeToComplete = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.EstimatedTimeToComplete,
                        ETID = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.ETID,
                        Id = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.Id,
                        IsValidationRequired = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.IsValidationRequired,
                        LeaveDate = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.LeaveDate,
                        Name = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.Name,
                        ScopeOfFiles = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.ScopeOfFiles,
                        SimultaneousEmployeeCount = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.SimultaneousEmployeeCount,
                        StateType = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.StateType,
                        TypeId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.TypeId,
                        ValidatorPrincipalId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.ValidatorPrincipalId,
                        ValidatorPrincipalType = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.ValidatorPrincipalType,
                        WorkflowId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowState.ProjectWorkflowId
                    },
                ParentWorkflowStateId = dtoProjectWorkflowTransition.ProjectWorkflow.ParentWorkflowStateId,
                Project = dtoProjectWorkflowTransition.ProjectWorkflow.Project,
                ProjectId = dtoProjectWorkflowTransition.ProjectWorkflow.ProjectId,
                ProjectWorkflowTemplateGroup = dtoProjectWorkflowTransition.ProjectWorkflow.ProjectWorkflowTemplateGroup,
                ProjectWorkflowTemplateGroupId = dtoProjectWorkflowTransition.ProjectWorkflow.ProjectWorkflowTemplateGroupId
            },
        SourceStateId = dtoProjectWorkflowTransition.InputStateId,
        WorkflowId = dtoProjectWorkflowTransition.ProjectWorkflowId
    })
```

**Comment by sdanyliv** [comment]
Maybe you can post also classes? Non comiplable. It will save my time.

**Comment by sdanyliv** [comment]
@detoxhby, good news i have reproduced bug. No additional data needed.

**Comment by detoxhby** [comment]
> @detoxhby, good news i have reproduced bug. No additional data needed.

Awesome!

**Comment by detoxhby** [comment]
What's up with failing build? I have about 1 more hour today to be able to rerun the tests with new version.

Please ping me when the new version is out on MyGet!

**Comment by MaceWindu** [comment]
it will be rc4672. publishing right now

**Comment by detoxhby** [comment]
✅ All good!

**Pull request merged**
