### PR TITLE
Test for issue #1261 - .All() generates incomplete WHERE

### PR DESCRIPTION
**Pull request by evilbloodydemon**

### CODE REVIEW

**Comment by evilbloodydemon** [comment]
@jogibear9988 why is that? they're just plain booleans

**Comment by jogibear9988** [comment]
sorry, you‘re right... i thought they return a list... silly

**Comment by jogibear9988** [comment]
Why does appveyor not fail?

**Comment by MaceWindu** [comment]
Because test disabled by [ActiveIssue] attribute

**Comment by evilbloodydemon** [comment]
@jogibear9988 because of ActiveIssue attribute

**Comment by jogibear9988** [comment]
ahhhh, I've not seen this...

**Pull request merged**
