### PR TITLE
Retry policy infrastructure

### PR DESCRIPTION
**Pull request by andrewvk**
Base contract for retry policy strategy and db access wrapping

### CODE REVIEW

**Comment by jogibear9988** [comment]
Is this to https://github.com/linq2db/linq2db/pull/735

**Comment by andrewvk** [comment]
No, it's just a coincidence. I prepare to move old azure project from EF (+ MS TransientFaultHandling) to linq2db, and retry policy support is critical.

**Comment by sdanyliv** [comment]
How it should work with transactions?

**Comment by andrewvk** [comment]
This version just ignore it, do all retries inside current TX (like EF Core or early variants for classic EF does). Later I will port a helper form EF Core to make retry of all transaction content or create something more implicit.

**Comment by sdanyliv** [comment]
Great. I saw EF implementation, that's why i'm asking ;)

**Comment by jogibear9988** [comment]
but if we include this, we can ignore #735?

**Comment by andrewvk** [comment]
I think yes, ignore it. Returning null for retrying is a highly non-obvious logic.

**Comment by ili** [comment]
@andrewvk for now retry is done only for queries, we do have 'DataConnection.InitConnection` method, it opens connection - the question is - should it be retried or not?

**Comment by andrewvk** [comment]
Fix it in master

**Comment by jogibear9988** [comment]
Can I use the same DbRetryPolicy (derived from RetryPolicyBase) for multiple DataConnections ? If I do so, is then maybe the retry counter wrong?

**Pull request merged**
