### PR TITLE
Exception interception issue #733

### PR DESCRIPTION
**Pull request by RoyC-Retail-Assist**
For issue #733 

Added virtual method that is called before a database exception is finally thrown to allow users to replace the database specific exception with a more generic one.

I can't find a mechanism to force a Exception for the ExecuteScalar method in the tests so suggestions would be welcome.

### CODE REVIEW

**Comment by MaceWindu** [comment]
Could you update your PR to use C# 5? Unfortunatelly we don't support C# 6+ in our codebase right now

**Comment by jogibear9988** [comment]
Can we change the Code so that also a retry is possible? For Example if "ExceptionIntercept" returns null?

**Comment by ili** [comment]
Interception is really needed or #736 is enough?

**Comment by RoyC-Retail-Assist** [comment]
#733 was to allow interception of Exceptions to allow re-throwing a different, database agnostic exception.  I only added in the retry code after @jogibear9988 made the suggestion as it wasn't much effort to include.

I can rework this to fit in with the #736 code changes without too much effort if it is likely to be pulled.

**Comment by jogibear9988** [comment]
Can't you also use the RetryPolicy to change the Exceptions? If you put a Try/Catch inside it, and throw a new Exception?

**Comment by RoyC-Retail-Assist** [comment]
I can wrap the Execute???Intenal methods introduced in #736 with the try/catch blocks in this PR and it should then allow the retry policy to run and the allow the interception of any resultant exception.

I'll just return the original exception if the user returns a null :o)

@ili Is this approach likely to be pulled?

**Comment by RoyC-Retail-Assist** [comment]
I've had a closer look at the RetryPolicy and I can, indeed, utilise it to be able to catch and then re-throw the exceptions.

I'll close this PR and then create a new one with a sample unit test that will demonstrate a solution to #733

**Pull request closed without merging**
