### PR TITLE
MySqlConnector 2.0.0 (and others) update

### PR DESCRIPTION
**Pull request by MaceWindu**
- Dependency Updates:
  - [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter): 4.0.0 -> 4.1.0
  - [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 1.3.14 -> 2.0.0
  - [Microsoft.SourceLink.GitHub](https://www.nuget.org/packages/Microsoft.SourceLink.GitHub): 1.0.0 -> 1.1.1
  - [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 3.1.20 -> 3.1.21
  - [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite): 5.0.11 -> 5.0.12
  - ~[Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite): 5.0.11 -> 6.0.0~ reverted, broken bad
  - ~[Npgsql](https://www.nuget.org/packages/Npgsql): 5.0.10 -> 6.0.0~ reverted, needs fixes around DateTime Kind (probably in tests)
  - [FirebirdSql.Data.FirebirdClient](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient): 8.5.3 -> 8.5.4
- Support native `BulkCopy` API changes in `MySqlConnector` 2.0.0 (Fix https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/194)
- Enabled testing of previous major versions of `MySqlConnector` to ensure we still maintain compatibility (old versions required at least for integration with older `EF.Core` versions)
- Disabled provider types testing for mysql on .net core 2.1 (don't want to add assembly aliases back just for couple of marginal tests on old framework and provider)
- removed [test](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Exceptions/DataExceptionTests.cs), that lost it's purpose 8 years ago
- `Npgsql` 6 in general works, but there are optional errors about DateTime `Kind.Unspecified`. Support for new/changed APIs will be added by next release
- `Microsoft.Data.Sqlite` 6.0.0 is completely broken, we need to wait for new version and probably report found issues

### CODE REVIEW

**Review by sdanyliv — APPROVED** [review]

**Comment by MaceWindu** [comment]
Microsoft.Data.Sqlite 6.0.0 fails badly...

**Comment by MaceWindu** [comment]
Just for notes one of issues we faced with new sqlite provider is #26574
Also there there is at least one threading issue, not yet reported to efcore repo and file lock issues, probably related to new connection pooling feature

**Comment by pavlo-dudka** [comment]
it seems you forgot to update linq2db/NuGet/MySql/LinqToDB.MySql.Tools.ttinclude, it still has reference to MySqlConnector 1.0, also System.Diagnostics.DiagnosticSource.dll (dependency of MySqlConnector 2.0) is missing in nuget

**Pull request merged**
