### PR TITLE
Fix C# init-only support for older TFMs

### PR DESCRIPTION
**Pull request by MaceWindu**
Critical issue discovered during https://github.com/linq2db/linq2db/pull/3530 testing.

Workaround to https://github.com/dotnet/runtime/issues/79082

### CODE REVIEW

**Comment by viceroypenguin** [comment]
How are we hitting this particular issue? Seems like an overly complicated setup in the first place. As long as we provide both pre/post `IsExternalInit` TFMs of l2db, that should be the extent of our requirement to handle.

**Comment by MaceWindu** [comment]
linq2db.aspnet is ns2.0-only

**Comment by viceroypenguin** [comment]
Seems like the proper fix would be to add additional TFMs to l2db.aspnet between ns2.0 and net7.0. Regardless, LGTM

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
it will not solve situations when user has mixed build setup

**Comment by Shane32** [comment]
By the way, we stopped using init-only properties (or provided workarounds in the form of constructors) over at GraphQL.NET when we discovered it currently requires a newer C# language version than would be default for .NET Framework applications. There’s no workaround either, besides bumping the language version in the consuming application, which is not always an acceptable option for large companies.

**Comment by viceroypenguin** [comment]
Not that this is a recommendation for l2db, because I think l2db should have broader support, but I've simply dropped support for below .net31 on most of my libraries.

**Comment by Shane32** [comment]
> Not that this is a recommendation for l2db, because I think l2db should have broader support, but I've simply dropped support for below .net31 on most of my libraries.

Ditto for Core, although .NET Framework 4.6.1 and newer are still supported by MS. In addition, just FYI, the ASP.Net Core 2.1 libraries are also officially supported by MS when used with .NET Framework, as newer versions of .NET Core do not work with .NET Framework. I recently added support to GraphQL.NET Server for those frameworks (and use them).

**Comment by Shane32** [comment]
> @Shane32 that's actually good point to be careful with new features. In this case we are safe - even with old targets users still can create records as they are just classes

👍

**Comment by Shane32** [comment]
For reference:
- https://github.com/graphql-dotnet/graphql-dotnet/issues/3322
- https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-framework
- https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#metadata-encoding

**Comment by viceroypenguin** [comment]
> > Not that this is a recommendation for l2db, because I think l2db should have broader support, but I've simply dropped support for below .net31 on most of my libraries.
> 
> Ditto for Core, although .NET Framework 4.6.1 and newer are still supported by MS. In addition, just FYI, the ASP.Net Core 2.1 libraries are also officially supported by MS when used with .NET Framework, as newer versions of .NET Core do not work with .NET Framework. I recently added support to GraphQL.NET Server for those frameworks (and use them).

Actually, due to an oddity in how netfx 3.5 was handled, it's technically under msft support until 2028. Go figure. Definitely not going to offer support that far back though.

**Pull request merged**
