### PR TITLE
Add linq2db.sqlite.ms nuget for Microsoft.Data.Sqlite provider

### LINKED ISSUE #1175: Xamarin. Sqlite. Build error
Visual Studio 2017

1. Create empty Xamarin Android XAML App project
2. Install linq2db.SQLite 1.9.0 nuget package
3. Build solution

``
Error		Exception while loading assemblies: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: C:\Users\mailm\.nuget\packages\system.runtime.loader\4.3.0\lib\MonoAndroid10\_._ ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   at Xamarin.Android.Tasks.ResolveAssemblies.ResolveRuntimeAssemblyForReferenceAssembly(LockFile lockFile, DirectoryAssemblyResolver resolver, String assemblyPath)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	App2.Android			``

Tried on x86 and x64 platforms.

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #1175 

I'm a bit tired how contentFiles work in different types of projects:
- for old projects they added as files
- for new projects like .net core they added as links
- for xamarin projects they don't added at all, but work

Remaining issues:
- [x] template files are not added to project tree for xamarin projects, so user need to add tt file using copy of sample file extracted from nuget/non-xamarin project

### CODE REVIEW

**Comment by MaceWindu** [comment]
Created issue for Microsoft guys, maybe there is some workaround (cannot find any yet). Otherwise we release it as is and document somewhere for xamarin developers.

https://github.com/dotnet/project-system/issues/3804

**Comment by MaceWindu** [comment]
Looks like starting with VS2017 15.8 it will work as expected for xamarin projects too

**Comment by jogibear9988** [comment]
see releasenotes for 1.0.109.0 https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki

**Comment by MaceWindu** [comment]
Well, in that case we need to add new package for ms implementation. Wasn't good idea to mix different providers

**Comment by jogibear9988** [comment]
Means? We close this pull req?

**Comment by MaceWindu** [comment]
No, I will redo it a bit later

**Comment by MaceWindu** [comment]
Ok, what we have:
- existing linq2db.sqlite package will remain the same
- we add new linq2db.sqlite.ms package for Microsoft's sqlite client implementation

Open questions:
- are everyone agree with new package naming? `linq2db.SQLite.MS`
- I didn't used Microsoft's client to new package tooling, as it doesn't make much sense to me to do it. Especially when it doesn't affect user's project

**Pull request merged**
