### PR TITLE
Fix loosing precision when DateTime has nanoseconds, but millissecond…

### PR DESCRIPTION
**Pull request by thechups**
…s = 0 and db column is datetime2.

For example: 
var dateTime = new DateTime(10000001);
and when database column is datetime2 with precision 7 string representation should be: '0001-01-01T00:00:01.0000001', but now it is: '0001-01-01T00:00:01'

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2727) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2727) before we can accept your contribution.<br/><br/>:x: thechups [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=2727)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=2727) it.</sub>

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
Could we have some tests?

**Comment by thechups** [comment]
> Could we have some tests?

Ok, i added test.

**Comment by thechups** [comment]
Add a separate test for my situation.

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
