### PR TITLE
Netcore

### PR DESCRIPTION
**Pull request by ili**
#304 fix

linq2db.core package supporting `net40`, `net45` & `netstandard1.6`

### CODE REVIEW

**Comment by jogibear9988** [comment]
I've written a mail to igor, if he still activly works on linq2db! 
I post here when I get an answer, if not, maybe we need to create a fork wich is maintained!

**Comment by ili** [comment]
I think he'll  be back :)

**Comment by ipashqa** [comment]
Are there any updates about it?

**Comment by ili** [comment]
Available on myget now see #304 there are feed address.
Also on same feed you can find identity storage provider :)

**Comment by ipashqa** [comment]
@ili 
Thank you, Ilya!
Is @igor-tkachev working on this pull request?

**Comment by ili** [comment]
@ipashqa not at all :)

speaking about @igor-tkachev I'm looking forward to contact him, but not yet succeed :(

**Comment by Reltik** [comment]
You are my hero dude!! Great job

**Comment by jogibear9988** [comment]
I also wrote him a E-Mail to his account 10 day ago, but I got no answer.

Maybe we could also ask @andrewvk, he seems to be also a member of the linq2db org at github.

If not, maybe we create a fork? I've also created a organization @ github, for a few .net projects (https://github.com/dotnetprojects), i could also include linq2db

**Comment by andrewvk** [comment]
I will contact to Igor and duscuss with him about this PR.

**Comment by ili** [comment]
Thanks @andrewvk :)

**Comment by jogibear9988** [comment]
still no answer? 

ili, what do you think about creating an official supported fork where we you a git repo together?

**Comment by ili** [comment]
Will be merged this week :)
I think i'll do it on weekend (to merge, test and release some other pull requests)

**Comment by jogibear9988** [comment]
Will this be a new nuget, or replace linq2db?

**Comment by jogibear9988** [comment]
and one more question, do you know what was planed with v2 branch? Will changes from there be merged back?

**Comment by ili** [comment]
New packet for now - because now there are problems to support SL & WindowsStore in `project.json`
No, i don't know what plans no Igor have on v2, but i suppose that v2 should support all v1 features :)

**Comment by jogibear9988** [comment]
I don't think core packed needs to support silverlight, as silverlight is almost dead!

**Comment by jogibear9988** [comment]
are you then now a new maintainer?2 is igor comming back?

**Comment by ili** [comment]
I do not :)
I'v just offered Igor my help in maintaining linq2db...

PS about dead SL... Windows XP is dead too but i do have plenty of customers using XP... and XP is .Net 4... Also speaking about enterprise solutions they are very conservative and nobody would rewrite software only because MS not supporting SL (I do also have customers using Visual Fox Pro solutions, and one of them few days ago asked for new feature) So for now core there would be two packages, may be in future when MS will release new core version it would be possible to merge them in one...

**Pull request merged**
