### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by MaceWindu**
- enable C#9
- fix NRT annotations for `Validation.ttinclude` template
- update dependencies
  - [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData) 7.5.1 -> 7.5.2
  - [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces) 1.1.1 -> 5.0.0
  - [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite) 3.1.9 -> 5.0.0
  - [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection) 3.1.9 -> 3.1.10
  - [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions) 3.1.9 -> 5.0.0
  - [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk) 16.7.1 -> 16.8.0
  - [MySqlConnector](https://www.nuget.org/packages/MySqlConnector) 1.0.1 -> 1.1.0
  - [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable) 1.7.1 -> 5.0.0
  - [System.ComponentModel.Annotations](https://www.nuget.org/packages/System.ComponentModel.Annotations) 4.7.0 -> 5.0.0
  - [System.Data.Odbc](https://www.nuget.org/packages/System.Data.Odbc) 4.7.0 -> 5.0.0
  - [System.Data.OleDb](https://www.nuget.org/packages/System.Data.OleDb) 4.7.1 -> 5.0.0
  - [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core) 1.0.113.1 -> 1.0.113.6
  - [Npgsql](https://www.nuget.org/packages/Npgsql) 4.1.5 -> 4.1.6

~Looks like OleDb provider finally usable with .net core (at least I don't see crashes after several testruns)~ nope, still crashes

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
npgsql just released 4.1.6 and 5.0.0 so also updated it to 4.1.6
update to 5.0.0 will be in separate PR later this week as it requires additional changes to support it properly and I really want to merge this PR asap

**Pull request merged**
