### PR TITLE
[DO NOT MERGE BEFORE 3.0] Fix typo in MappingSchema and MappingSchemaInfo

### PR DESCRIPTION
**Pull request by CoskunSunali**
Nothing fancy, just fixes two or three typos.

### CODE REVIEW

**Comment by MaceWindu** [comment]
Thanks!

**Comment by MaceWindu** [comment]
This semver thing is annoying :)

**Comment by CoskunSunali** [comment]
I realized I created a pull request for the master branch instead of a separate branch. Sorry for that.

You prefer separate branches, don't you? Just to be sure for future pull requests.

**Comment by MaceWindu** [comment]
Actually it's good you asked. I planned to create v3 branch today or early next week and merge this PR here, so if you can just update it with latest master, it will help.

And yes, PRs against new branch is always better, but not a big issue at this moment.

**Comment by CoskunSunali** [comment]
I actually wanted to merge the changes from master yesterday but there were so many conflicts, I gave up.

I am not even sure why I get conflicts. My fork's master only has the mentioned typo changes and basically I should be able to rebase my master onto yours without any conflicts at all.

I will summarize what I do below, what does seem to be wrong to you?

```bash
git clone https://github.com/CoskunSunali/linq2db.git
cd linq2db
git pull https://github.com/linq2db/linq2db.git master

git status

On branch master
Your branch and 'origin/master' have diverged,
and have 261 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

git pull
```

And I end up with plenty of conflicts.

My computer is set to use `--rebase` option along with a `git pull` command.

**Comment by MaceWindu** [comment]
actually it merged into 3.0 branch without requesting any merges

**Pull request merged**
