### PR TITLE
Fix issue #1007 - Merge entity with identity in ms sql

### PR DESCRIPTION
**Pull request by LbISS**
#1007

### CODE REVIEW

**Comment by sdanyliv** [comment]
Thanks, for PR. Could you please create unit test for this issue?

**Comment by LbISS** [comment]
Ok, I've tried but it's not that simple. I'll look into it later. Contributing.md in project and https://github.com/linq2db/linq2db/wiki/Contributor-Guide are contradicting in section about DataProviders settings. And is rather misguiding that project named "Tests" laying in "Test.Linq" folder. And contains "Linq" folder itself.

**Comment by sdanyliv** [comment]
@LbISS, it’s a little bit outdated documetation.
Check this file. Read comment at the top of the file.
https://github.com/linq2db/linq2db/blob/master/Tests/DataProviders.json

**Comment by MaceWindu** [comment]
Thanks for your contribution! I'm taking this issue over. Will create new tests

**Comment by MaceWindu** [comment]
Closing, fix tracked by https://github.com/linq2db/linq2db/pull/1011

**Pull request closed without merging**
