### PR TITLE
Update MySqlConnector to 1.0

### PR DESCRIPTION
**Pull request by bgrainger**
MySqlConnector 1.0 changes the primary namespace to `MySqlConnector`: mysql-net/MySqlConnector#824; this updates all relevant code.

This starts the discussion around updating MySqlConnector to 1.0, but doesn't need to be merged until it's out of beta.

### CODE REVIEW

**Comment by MaceWindu** [comment]
Thanks!
I think we will drop support for MySqlConnector < 1.0.0 if nobody will request support. We can support older versions, but don't see a reason to do it for now.

**Comment by bgrainger** [comment]
Updated MySqlConnector 1.0 and rebased PR.

**Pull request merged**
