### PR TITLE
t4 template fix for "assembly can't be resolved" on macos

### PR DESCRIPTION
**Pull request by pavlo-dudka**

### CODE REVIEW

**Comment by MaceWindu** [comment]
Thanks. Need to check it still works for Visual Studio, but looks ok

**Comment by MaceWindu** [comment]
Actually no, this fix will break use from VS as VS uses shadow copy. I will edit it a bit to use location only for non-vs hosts

**Comment by pavlo-dudka** [comment]
sorry if it brakes template on Windows/VS
please adjust the changes as needed
the problem on MacOs is caused by removing "file:///", while only "file://" needs to be removed, e.g.
"file:///Users/pdu/.nuget/packages/linq2db.mysql/3.4.5/tools/linq2db.dll" should be changed to "/Users/pdu/.nuget/packages/linq2db.mysql/3.4.5/tools/linq2db.dll"

**Comment by MaceWindu** [comment]
Please check it works after my change.

**Comment by MaceWindu** [comment]
According to documentation it's even worse https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.codebase?view=net-5.0
under .net 5+ it will throw exception, but we still need to use it for .net framework

**Review by MaceWindu — APPROVED** [review]

**Comment by pavlo-dudka** [comment]
> Please check it works for you after my change.

works fine, thank you

**Comment by pavlo-dudka** [comment]
CodeBase property is also used in LinqToDB.Common.Tools.GetFileName, please consider to refactor it too

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
