### PR TITLE
Initial Firebird 4 support (+ Update dependencies)

### PR DESCRIPTION
**Pull request by MaceWindu**
- Update dependencies
  - [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 1.3.2 -> 1.3.3
  - [Npgsql](https://www.nuget.org/packages/Npgsql): 4.1.8 -> 4.1.9
  - [Npgsql](https://www.nuget.org/packages/Npgsql): 5.0.3 -> 5.0.4
  - [Microsoft.Data.SQLite](https://www.nuget.org/packages/Microsoft.Data.SQLite): 5.0.4 -> 5.0.5
  - [FirebirdSql.Data.FirebirdClient](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient): 7.5.0 -> 7.10.1 / 8.0.1
  - [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 3.1.13 -> 3.1.14
  - ~[Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk): 16.8.3 -> 16.9.4~ still complete junk
  - [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter): 4.0.0-beta.1 -> 4.0.0-beta.2
  - [FastExpressionCompiler](https://www.nuget.org/packages/FastExpressionCompiler): 3.0.0 -> 3.0.4
  - [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData): 7.5.6 -> 7.5.7
- Support new functionality from `FirebirdSql.Data.FirebirdClient` (pick already implemented stuff from #2693 and add more changes)
  - add Firebird 4 test provider
  - add Firebird 4 to CI (using RC1)
  - add new Firebird 4 types support (see below)
  - remapped `Sql.CurrentTimeStamp` from `CURRENT_TIMESTAMP` to `LOCALTIMESTAMP` so it continue to work against FB4
  - remapped `RTRIM` and `LTRIM` UDFs to `TRIM(LEADING/TRAILING FROM {0})` as UDFs was removed from Firebird 4
- fixed issue when `from` -> `to` conversion were looking for existing `explicit`/`implicit` conversion operator only in target type
- included `Microsoft.Bcl.AsyncInterfaces.dll` to all T4 nugets to avoid errors from vistual studio when running template
- updated `Firebird` table columns schema loader to not load `precision`/`scale`/`length` properties on types that doesn't support them (leads to more clean T4 outputs)
- updated parameters load for `Firebird` `FOR SELECT` procedures to exclude output parameters that duplicate resulting table columns (more clean T4 outputs)

#### Firebird 4 support

- new type: `DECFLOAT`/`DECFLOAT(16)` mapped to `FbDecFloat` (`DataType.DecFloat`)
- new type: `TIMESPAN WITH TIME ZONE` mapped to `FbZonedDateTime` (`DataType.DateTimeOffset`)
- new type: `TIME WITH TIME ZONE` mapped to `FbZonedTime` (`DataType.TimeTZ`)
- new type: `INT128` mapped to `BigInteger` including literals support (`DataType.Int128`)
- new types support also includes support in schema API and T4 templates

There is no literals generation support out-of-box for `DECFLOAT` and time-zoned types as is is not always possible to generate literals for them.

Note that at least 8.0.1 version of provider required (previous versions contain bugs in FB4 support area)

### CODE REVIEW

**Comment by MaceWindu** [comment]
Should be ready. I've disabled 3 tests that test async api with cancelled token for Firebird as provider added async API, but implemented it a bit incorrectly (we had same issue with npgsql 5, so I'm going to report another issue).

testing SDK update failed again. Something strange happens with 16.9.x versions and I don't have much time to investigate it

**Review by sdanyliv — APPROVED** [review]

**Comment by MaceWindu** [comment]
Firebird provider issue to track for disabled async tests  https://tracker.firebirdsql.org/browse/DNET-1043

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
