### PR TITLE
Added some overloads accepting sql parameters as object

### LINKED ISSUE #2089: Add extention method for queryproc to simplify parameter specification
Somebody already guessed this in some issue's comments, but it's still not implemented..

I want to query stored proc's using anonymous type as a parameter storage:

Db.QueryProc<MyType>("myStoredProc", new {TypeID = 55, CloseDate = DateTime.Now.Date});

It's a pain working with dataparameter[]

### PR DESCRIPTION
**Pull request by feeleen**
Fixes #2089

### CODE REVIEW

**Comment by sdanyliv** [comment]
Thanks for that!
Even such simple tasks help us to improve usability. We appreciate any help, there are a lot of urgent tasks to do and we can not switch from process.

**Comment by sdanyliv** [comment]
Please try that overloads do not fall in collision with other methods, that's all.

**Comment by feeleen** [comment]
@sdanyliv do you want me to add some additional tests to the Test project for this? or just check than calling this overrides will compile? I added some calls in a test project like

`var set32 = db.QueryProc<VariableResult>("[VariableResults]",
					new { ReturnFullRow = 1 }).First();`

it does compile

**Comment by sdanyliv** [comment]
I would prefer to make test call using each overload.
We need that for regression detection. It really helps when we refactor legacy parts.
There are already QueryProc calls in our tests, we just need to duplicate them using this new overload.

Thanks!

**Comment by feeleen** [comment]
fixed my copy/paste typo in a test project.. )

**Pull request merged**
