### PR TITLE
Added ANY functions for arrays.

### LINKED ISSUE #1660: postgres Array queries do not seem to be supported!
[Table(Name = "dd")]
public partial class dd
{
        [Column(Name = "dd", DataType = DataType.VarChar, Length = 255)]
        public System.String[] source { get; set; }
}

using (var con = DB.GetConnection())
 {
      var sql = con.Entity.dd.Where(c => c.source.Contains("2"));
      var data2 = sql.ToList();
}

throw:
LinqToDB.Linq.LinqException:“'c.source.Contains("2")' cannot be converted to SQL.”

### PR DESCRIPTION
**Pull request by sdanyliv**
Partially fixe_s #1660

### CODE REVIEW

**Review by MaceWindu — APPROVED** [review]

**Comment by Evengard** [comment]
Does this support standart linq methods such as Contains and/or Any? Or it is a special method only?

**Comment by MaceWindu** [comment]
for now special methods only.
Not sure we should map generic `Contains`/`Any` methods by default. @sdanyliv ?

**Comment by sdanyliv** [comment]
We can, but it needs additional effort.

**Comment by Evengard** [comment]
Well, people first impulse would to attempt to use the generic Any/Contains methods first, only to end up with an exception. While, for example, window functions do need some explicit syntax, the array type is basically an enumeration, so seems logical to work with it like with any other enumerations... And the "ANY()" method from pgsql seems to be logical to be mapped to Linqs Any, even the names match.

That's just my two cents though. I have no ideas how hard is it, as it is a really complex library.

**Pull request merged**
