### PR TITLE
trying to fix test fail after #521

### PR DESCRIPTION
**Pull request by ili**
One test failed after merging #521

### CODE REVIEW

**Comment by jogibear9988** [comment]
When you look at the appveyor result from my pull req: https://ci.appveyor.com/project/igor-tkachev/linq2db-8c54d/build/1.7.6.265/tests all test work

**Comment by ili** [comment]
@jogibear9988 yes, Core configuration succeed.

Also all tests are succeed on my home and work machine. Only fails on AV... I do think this is because of different test order...

But in anyway, we do have the situation where some tests are failed. I think we should revert this change.

**Comment by jogibear9988** [comment]
dont think we should revert, we should find the issue!

**Comment by jogibear9988** [comment]
i'll look into it

**Comment by ili** [comment]
All tests are succeed...
Please take a look, because i have no idea what for this block was introduced...

**Comment by ili** [comment]
@jogibear9988 i'll merge this fix for now.

If this code block is really needed, please, make separate PR

**Pull request merged**
