### PR TITLE
Update ValueTaskToTaskMapper.cs

### LINKED ISSUE #2364: LinqToDB.LinqToDBException: ValueTaskToTaskMapper mapper applied to non-ValueTask type (current develop + branch)
I'm geeting following Exception when using current linq2db develop + branch from https://github.com/linq2db/linq2db/pull/2357
when using our newest version against PostgreSQL

   at LinqToDB.Expressions.ValueTaskToTaskMapper.LinqToDB.Expressions.ICustomMapper.Map(Expression expression) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\ValueTaskToTaskMapper.cs:line 18
   at LinqToDB.Expressions.TypeMapper.<>c__DisplayClass23_1.<MapLambdaInternal>b__3(Expression e) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 682
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\Extensions.cs:line 1007
   at LinqToDB.Expressions.TypeMapper.<>c__DisplayClass23_0.<MapLambdaInternal>g__ReplaceTypes|2(Expression expression) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 428
   at LinqToDB.Expressions.TypeMapper.MapLambdaInternal(LambdaExpression lambda, Boolean mapConvert, Boolean convertResult, Boolean ignoreMissingMembers) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 696
   at LinqToDB.Expressions.TypeMapper.BuildWrapperImpl(LambdaExpression lambda, Boolean wrapResult, Boolean optional) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 1067
   at LinqToDB.Expressions.TypeMapper.BuildWrapper(LambdaExpression lambda, Boolean optional) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 1062
   at LinqToDB.Expressions.TypeMapper.<BuildWrapperMethods>b__17_1(<>f__AnonymousType114`2 e) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 348
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LinqToDB.Expressions.TypeMapper.BuildWrapperMethods(Type wrapperType) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 344
   at LinqToDB.Expressions.TypeMapper.FinalizeMappings() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 196
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\NpgsqlProviderAdapter.cs:line 194
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs:line 22
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLTools.cs:line 18
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

### PR DESCRIPTION
**Pull request by jogibear9988**
fixes #2364

### CODE REVIEW

**Comment by MaceWindu** [comment]
Could you add test for ValueTask and ValueTask<T> for this mapper for netcore test target? we already have test for custom mapper in general, but we don't test https://github.com/linq2db/linq2db/blob/master/Tests/Linq/TypeMapping/MappingTests.cs#L708 but no tests for ValueTaskToTaskMapper :-/

**Comment by Shane32** [comment]
I don't have much input here; @MaceWindu added the `ValueTypeToTypeMapper` class.  I'm only noticing that we are comparing the type name to a string ... but that's necessary since we don't have a reference to `ValueType` on .Net Framework even though the mapping may still be necessary.  There are a few things that could be tested in case the current suggestion fails:
* `|| (expression.Type.IsGenericType && expression.Type.BaseType.FullName == "System.Threading.Tasks.ValueTask")`
* `expression.Type.FullName.StartsWith("System.Threading.Tasks.ValueTask")`

**Comment by Shane32** [comment]
(If it runs now, it looks good to me.)

**Comment by jogibear9988** [comment]
@MaceWindu okay so?

**Pull request merged**
