### PR TITLE
Added possibility to Disable Grouping Guard in query.

### PR DESCRIPTION
**Pull request by sdanyliv**
@detoxhby, please review also. 

Original conversation: https://github.com/linq2db/linq2db/issues/1764#issuecomment-638169815

### CODE REVIEW

**Comment by detoxhby** [comment]
Ah, seems like the direct native `IGrouping<TKey, TElement>` overload is missing and cannot be used in LINQ expression:
```csharp
for user in ctx.Users
group user by user.Type into g
select new UserTypeDescriptor()
{
    UserType = g.Key,
    Users = g.DisableGuard().ToList() // g is IGrouping<,> type here here as range variable
}
```

**Comment by sdanyliv** [comment]
I’ll check this variant. But in this case, better to put AsEnumerable(), always.

**Comment by sdanyliv** [comment]
If i can detect this variant, i can make AsEnumerable() call automatically ))
Here i need to think.

**Pull request merged**
