### PR TITLE
Fix MergeWithOutputInto with conditional in output expression

### PR DESCRIPTION
**Pull request by poizan42**
This makes the test included in the commit work instead of throwing a NotImplementedException.

I had a hard time figuring out what IsExpression is actually supposed to do. It asks whether an expression is an expression (?), and the comments are less than helpful. It's something about whether the (linq) expression can be turned into a valid SQL expression in the current context? - but then what does it mean when expression is null?

I figured the worst that can happen is that incorrect sql is produced now where it previously crashed with NotImplementedException. It at least makes this case work, and can't affect anything that didn't crash before.

### CODE REVIEW

**Comment by poizan42** [comment]
The test-all and test-all (Tests: Linux MariaDB) checks are broken?

**Comment by MaceWindu** [comment]
just glith, restarted failed run

**Comment by poizan42** [comment]
Didn't help, now test-all just failed after 7 minutes without logging anything

**Comment by MaceWindu** [comment]
ignore it, looks like mariadb docker image is broken or something changed with its setup

**Comment by MaceWindu** [comment]
probably caused by https://github.com/MariaDB/mariadb-docker/issues/512

**Review by MaceWindu — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]

**Review by igor-tkachev — APPROVED** [review]

**Pull request merged**
