### PR TITLE
Add AsValueInsertable

### PR DESCRIPTION
**Pull request by MihailsKuzmins**
Issue #3327

### CODE REVIEW

**Comment by sdanyliv** [comment]
Nicely done. But we need test when no `Value` is called. Probably it will fail, but we need to figure out what to do with that.

**Comment by MihailsKuzmins** [comment]
Good catch. The values block will be empty so it will fail. I would say that it is a mistake of the developer, not Linq2DB.
But if you have some suggesstions (sorry, I am not experienced to offer something), we could try it 😃

**Comment by to11mtm** [comment]
> Good catch. The values block will be empty so it will fail. I would say that it is a mistake of the developer, not Linq2DB. But if you have some suggesstions (sorry, I am not experienced to offer something), we could try it 😃

We probably don't need to get very fancy. Can we just start with a test that tries to call the insert without any `.Value()`s added and see what it does? Example:

```
[Test]
		public void AsValueInsertableEmptyThrowsTest([DataSources(TestProvName.All] string context)
		{
			using (var db = GetDataContext(context))
			using (var table = db.CreateLocalTable<TestInsertOrReplaceTable>())
			{
				var vi = table.AsValueInsertable();

				Assert.Throws(/*???*/,()=> vi.Insert());
			}
		}
```

Ideally, the exception should have a message that may help the user understand that no .Value()s were passed in.

**Comment by Usaga** [comment]
If Values block is empty it is not a mistake. It shouldn't throw or fail any way. This insert operation may be conditional. Like `SaveChanges()` in EF which will do nothing if nothing has changed\inserted.

Programmer may check what `Insert()` returns, and if it return zero (nothing was inserted), then he\she\it may react the way he\she\it wants.

Fail may be needed if we meet some kind of uncertainty.

**Comment by to11mtm** [comment]
You could probably get away with returning a different value for the basic
.Insert case, but InsertWithInt32/64Identity would have potentially
ambiguous behavior short of erroring out.

**Comment by MihailsKuzmins** [comment]
When I run a unit test for `IValueInsertable` without any properties the error message is **really bad** since `insert.Into` is null:
*InsertBuilder.cs line 216*
image

I can only suggest:
- throw another more meaningful exception here
- wrap the foreach block in the if block which checks `insert.Into` for null. There are further null reference errors in `BuildPhysicalTable` where the argument table is null since `insertClause.Into` is passed to it

**Review by MaceWindu — APPROVED** [review]

**Comment by MaceWindu** [comment]
@MihailsKuzmins thanks!

**Comment by MihailsKuzmins** [comment]
@MaceWindu thank you for merging the change :)

**Pull request merged**
