### PR TITLE
Do not convert simple constant to the SQL for projection.

### LINKED ISSUE #4559: [Task] Firebird 2.5 provider could emit unnecessary '1' (true) constant column
Discovered by [EnumerableSourceTests.ConstantProjection](https://github.com/linq2db/linq2db.baselines/pull/1253/files#diff-ef050fd666a2a666cca2eac34b18479029bc230ec76e7589ca7cf618afe861ed)  and [EnumerableSourceTests.NullConstantProjection](https://github.com/linq2db/linq2db.baselines/pull/1253/files#diff-ed385df919e6ea8a654f6feab93f66ef78cb3592a175f829563e39db76528d89) tests

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #4559

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by igor-tkachev** [comment]
Does it support method `Sql.AsSql`? It should generate SQL if it's used.

**Review by MaceWindu — APPROVED** [review]

**Comment by sdanyliv** [comment]
@igor-tkachev, sure `Sql.AsSql` will force constant conversion to the SQL.

**Pull request merged**
