### PR TITLE
Fixed integration with third party extensions.

### LINKED ISSUE #4519: Adding AsExpandable() from LinqKit with extra predicate leads to parsing fail
### Adding AsExpandable() from LinqKit with extra predicate leads to parsing fail

```
Exception message:
must be reducible node
Stack trace:
Exception: System.ArgumentException
must be reducible node
   at Expression System.Linq.Expressions.Expression.VisitChildren(ExpressionVisitor visitor)
   at Expression System.Linq.Expressions.ExpressionVisitor.VisitExtension(Expression node)
   at Expression System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Expression LinqToDB.Expressions.SqlQueryRootExpression.Accept(ExpressionVisitor visitor) in E:/edams500/Tools/LinqToDB/Source/LinqToDB/Expressions/SqlQueryRootExpression.cs:line 103
   at Expression System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Expression[] System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at Expression System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Expression LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m)
   at Expression System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Expression System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Expression[] System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at Expression System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Expression LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m)
   at Expression System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at Expression System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Expression LinqKit.ExtensionsCore.Expand(Expression expr)
   at IQueryable<TElement> LinqKit.Core.ExpandableQueryProvider<T>.System.Linq.IQueryProvider.CreateQuery<TElement>(Expression expression)
   at IQueryable<TSource> System.Linq.Queryable.Where<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate)

```

### Steps to reproduce

```c#
      if (names.Any())
      {
        var predicate = PredicateBuilder.New<Item>(false);
        foreach (var name in names)
          predicate = predicate.Or(i => Sql.Like(i.Name, "%{0}%".Args(name)));

        var items = dc.Item.AsExpandable().Where(predicate);

        query = query.Where(i => items.Any(o => o.Id == i.Item.Id));
      }

```

### Environment details

`Linq To DB` version: 6.0.0.0

Database (with version): SQL Server 2017

ADO.NET Provider (with version): Microsoft.Data.SqlClient 3.1.15

Operating system: Windows 10

.NET Version: 4.8

LinqKit: 1.2.5

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #4519

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Review by MaceWindu — APPROVED** [review]

**Comment by MaceWindu** [comment]
Changes to [ParameterTests.Caching(SqlServer.SA.LinqService).sql](https://github.com/linq2db/linq2db.baselines/pull/1223/files#diff-2ac53433be66bf0745851ec463fec39006e86a0f49f6787f55e6193a1eb87924) baselines are worrying

**Pull request merged**
