### PR TITLE
Additional Oracle Bulkcopy Insert Method to improve performance

### PR DESCRIPTION
**Pull request by laurentKTR**
Change type of UseAlternativeBulkCopy from bool to enum => Update Oracle Unit test

### CODE REVIEW

**Comment by sdanyliv** [comment]
@laurentKTR, before reviewing. Have you checked performance of Merge?
https://github.com/linq2db/linq2db/wiki/Merge-API

**Comment by laurentKTR** [comment]
We are actually using merge syntax mainly to update data on a table that contains 300 millions lines per year but we didn"t give a try for insert only operations => i will have a look 
We are adding 1 million lines per day in this table using several methods : sqlLoader and bulkcopy

We have migrated from BLToolkit to Linq2db and noticed that the performance has decreased greatly 
the difference was the insert syntax used, it's the reason why i have added this "bltoolkit" syntax

**Comment by laurentKTR** [comment]
ok so i have performed some tests:
Using the method "Addtional Bulkcopy Insert Method " : 50 s to insert 10 000 lines
Using the merge, i have cancelled the operations after 6 mins for 6000 lines

This is the syntax i have used for merge:
dataContext.GetTable<T>().Merge().Using(elems).On((p,j) => false).InsertWhenNotMatched().Merge()
which generate a sql query : ON ( 1 = 0 ) => fast as it doesn't compare any primary key

**Comment by sdanyliv** [comment]
Great, we will review this PR soon. Possibly it can be deivered with the next release.

**Comment by laurentKTR** [comment]
I have noticed that you probably have a "column type" problem in merge command

I have declared my date property with DataType = DataType.Date
and the generated sql use TO_TIMESTAMP instead of TO_DATE
=> in oracle it's a killing performance convertion

it was a bug already fixed in a previous issue #487  for basic operations ( insert/update/select) : 
Looking in bulkcopy code you are using it dataConnection.MappingSchema.GetDataType(column.MemberType).DataType
but i didn't find trace of this method in BasicMergeBuilder

=> it might be why the performance is so bad

**Comment by laurentKTR** [comment]
hi

I had a look at Merge and it looks like for oracle you are not using parameters but plain value
so the problem seats in OracleMappingSchema.ConvertDateTimeToSql
I'm not sure how to proceed : open another pull request or continue in this one even if the subject is not anymore bulkcopy but merge?

**Comment by sdanyliv** [comment]
I think new PR would be great.

**Comment by laurentKTR** [comment]
ok

**Comment by laurentKTR** [comment]
I have kept the same behaviour by assigning the default value to the existing default method 
because i was not sure if you prefer to : 
keep the same functionality and user must toggle something to have benefit of "new feature" 
or
assign the "new feature" by default

**Comment by sdanyliv** [comment]
Looks like you are trying to emulate OracleBulkCopy from Oracle.DataAccess.dll.
So you have to vote ;)
https://apex.oracle.com/pls/apex/f?p=18357:39:5439210162954::NO::P39_ID:27881

**Comment by laurentKTR** [comment]
voted :-) 
the native bulkcopy is already in linq2db but i don't use it as it doesn't support transaction 
https://github.com/linq2db/linq2db/pull/635

**Pull request merged**
