### PR TITLE
Add Sql.TryConvert extension

### LINKED ISSUE #2936: [Feature] Add try_convert function
What do you think about adding `try_convert` next to Sql.Convert function?

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #2936

Support:
- SQL Server 2012+
- Oracle 12.2+

gonna check if other providers have something similar

### CODE REVIEW

**Review by sdanyliv — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
m'kay, no similar functionality in other dbs

**Comment by MaceWindu** [comment]
I will add another extension `TryConvertOrDefault` to support non-null replacement value for oracle

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
