### PR TITLE
Correct DeleteWithOutputAsync() function name

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Comment by sdanyliv** [comment]
Well, looks like we do not have regression test for this function ;)

**Comment by viceroypenguin** [comment]
pish posh. :D

**Comment by sdanyliv** [comment]
And missed again. Tested on Sync version.

**Comment by viceroypenguin** [comment]
Yes, all of the tests were only done w/ the sync version. Only added sync to match the other sync tests. I can double all of the tests for the async versions if you want? Seems somewhat extraneous, but...

**Comment by sdanyliv** [comment]
Believe me it worth efforts. We can accidentally change something and async versions may fail.

**Comment by viceroypenguin** [comment]
PS: Blame @MaceWindu  - he's the one who wrote the InsertWithOutput tests that I copied from originally... 😉

**Comment by sdanyliv** [comment]
It's me ;) Really messed up with count of new methods.

**Comment by viceroypenguin** [comment]
There. Punk... :)

**Review by sdanyliv — APPROVED** [review]

**Review by MaceWindu — CHANGES_REQUESTED** [review]
tests fail, probably something wrong with asserts

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
