### PR TITLE
Do not remove LEFT JOIN if there is table hint.

### PR DESCRIPTION
**Pull request by sdanyliv**
Wrong JOIN optimization with Temporal Tables.

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by jods4** [comment]
@sdanyliv out of curiosity, what's the underlying issue?
I don't see why it would be wrong to remove the LEFT JOIN in the test case you created?

Is it a cardinality problem with temporal ranges (your test case uses AS OF, so only it should return only 1 row)?

**Review by MaceWindu — APPROVED** [review]

**Comment by sdanyliv** [comment]
@jods4. with temporal tables here can be duplicates of Primary Key. Removing joins is not an option in that case. We can simplify restriction for `TemporalTableAsOf`, but not for `TemporalTableAll`. Decided to disable optimization for any hints right now.

**Comment by MaceWindu** [comment]
yep, join with temporal table could produce multiple records (not in this test)

**Comment by sdanyliv** [comment]
It is question to current hint implementation. I've just noticed that we have issue with this one and in production it may lead in problems. Since I have no time to work with this right now - disabled optimization for tables with hints. Will add comment about that when tests are passed.

**Comment by jods4** [comment]
@sdanyliv I see this was merged, please don't forget to add a comment so we remember why this was added and could potentially refactor it in the future.

**Comment by jods4** [comment]
@sdanyliv Understood, no problem if you need a fix for a bug in production.

Just for long-term maintenance I think we need to remember to add a test that would fail if this is removed and a comment to explain for what specific case we keep LEFT JOIN with hints.

**Pull request merged**
