### PR TITLE
Updates + .NET 7 SDK migration

### PR DESCRIPTION
**Pull request by MaceWindu**
- use .NET 7 SDK for build
- enable .NET 7 testing
- enable `net7.0` build (not released) target for non-test code to consume updated NRT runtime annotations
- address new code analysis errors (no new rules explicitly enabled, only new reports from new rules in 17.4 and from already enabled rules, improved in 17.4)
  - [CA1854](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854): `Prefer the IDictionary.TryGetValue(TKey, out TValue) method`
  - [CA1851](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1851): `Possible multiple enumerations of IEnumerable collection`
  - `IDE0200: Remove unnecessary lambda expression`
  - `IDE0250: Make struct 'readonly'`
  - `CA1852`: seal unsealed non-public classes
  - use invariant culture instead of current where appropriate for upper/lower conversions
  - use null-propagation `?.` operator instead of `if { ... }`
- add `ClickHouseDecimal` type support
- re-enable `ClickHouse.Client` provider testing on CI
- update dependencies:
  - [FirebirdSql.Data.FirebirdClient](https://www.nuget.org/packages/FirebirdSql.Data.FirebirdClient): 9.0.2 -> 9.1.0
  - [FSharp.Core](https://www.nuget.org/packages/FSharp.Core): 6.0.6 -> 7.0.0
  - [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData): 7.5.14 -> 7.6.1
  - [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces): 6.0.0 -> 7.0.0
  - [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite): 6.0.9 -> 7.0.0
  - [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 6.0.0 -> 7.0.0
  - [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk): 17.3.2 -> 17.4.0
  - [MySql.Data](https://www.nuget.org/packages/MySql.Data): 8.0.30 -> 8.0.31
  - [MySqlConnector](https://www.nuget.org/packages/MySqlConnector): 2.1.13 -> 2.2.1
  - [NodaTime](https://www.nuget.org/packages/NodaTime): 3.1.3 -> 3.1.5
  - [Npgsql](https://www.nuget.org/packages/Npgsql): 7.0.0-rc.1 -> 7.0.0
  - [System.Text.Json](https://www.nuget.org/packages/System.Text.Json): 6.0.6 -> 7.0.0
  - [System.Data.SqlClient](https://www.nuget.org/packages/System.Data.SqlClient): 4.8.3 -> 4.8.5
  - [System.Data.OleDb](https://www.nuget.org/packages/System.Data.OleDb): 6.0.0 -> 7.0.0
  - [System.Data.Odbc](https://www.nuget.org/packages/System.Data.Odbc): 6.0.1 -> 7.0.0
  - [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable): 6.0.0 -> 7.0.0
  - [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core): 2.19.160 -> 2.19.170
  - [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core): 3.21.70 -> 3.21.80
  - [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess): 21.7.0 -> 21.8.0
  - [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess): 19.16.0 -> 19.17.0
  - [NUnit3TestAdapter](https://www.nuget.org/packages/NUnit3TestAdapter): 4.2.1 -> 4.3.1
  - [System.Configuration.ConfigurationManager](https://www.nuget.org/packages/System.Configuration.ConfigurationManager): 6.0.1 -> 7.0.0
  - [System.Linq.Dynamic.Core](https://www.nuget.org/packages/System.Linq.Dynamic.Core): 1.2.20 -> 1.2.23
  - [protobuf-net.Grpc.AspNetCore](https://www.nuget.org/packages/protobuf-net.Grpc.AspNetCore): 1.0.177 -> 1.0.179
  - [protobuf-net.Grpc](https://www.nuget.org/packages/protobuf-net.Grpc): 1.0.177 -> 1.0.179
  - [FluentAssertions](https://www.nuget.org/packages/FluentAssertions): 6.7.0 -> 6.8.0
  - [ClickHouse.Client](https://www.nuget.org/packages/ClickHouse.Client): 5.1.1 -> 6.2.0
  - [Mono.TextTemplating](https://www.nuget.org/packages/Mono.TextTemplating): 2.2.1 -> 2.3.1
  - [Microsoft.Extensions.DependencyModel](https://www.nuget.org/packages/Microsoft.Extensions.DependencyModel): 6.0.0 -> 7.0.0
  - [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client): 2.49.0 -> 2.50.0
  - [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp): 4.3.1 -> 4.4.0
  - [Microsoft.SqlServer.Types](https://www.nuget.org/packages/Microsoft.SqlServer.Types): 160.900.6-rc0 -> 160.1000.6
  - [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core): 1.0.116 -> 1.0.117

### CODE REVIEW

**Comment by MaceWindu** [comment]
mkay, looks like we need to wait for azure update. Not exited to fix isues that will go away after update

**Comment by jogibear9988** [comment]
maybe we should also anouce there is a problem with net7 hotreload and propertyinfo when we merge this? Does anyone of you get issues with some of the tests, or do all work (when run inside of visual studio)?
It will be fixed in next Net7 release (i hope)

**Comment by MaceWindu** [comment]
not buildable as vs 17.4 not available yet on azure

**Review by sdanyliv — APPROVED** [review]

**Pull request merged**
