### PR TITLE
remove .net core 2.1 support

### PR DESCRIPTION
**Pull request by MaceWindu**
- removed explicit `.net core 2.1` support (users still can use `linq2db` there with `netstandard2.0` builds). 2.1 reached EOL last year and it became a PITA to support builds with tooling changes
- cleanup dependencies, drop testing of some very old versions of providers
- cleanup/fix incorrect #if-defs
- added async version of `DisposeCommand` method to fix detected sync-over-async cases
- update `ExecuteScope` method to support async to fix detected sync-over-async cases
- switch to `System.Text.Json` in tests from `newtownsoft.json`
- removed PostgreSQL 9 from CI testing
- removed `windows-2016` image use as it will be removed soon from Azure. ~No SQL Server NETFX tests for now as we don't have suitable docker images~ repelacement images found!

Remaining tasks:
- Ensure CI testing still works
  - [x] Access
  - [x] DB2
  - [x] Firebird
  - [x] Informix
  - [x] MySQL/MariaDB
  - [x] Oracle
  - [x] PostgreSQL
  - [x] SAP HANA 2
  - [x] SQL CE
  - [x] SQLite
  - [x] SQL Server
  - [x] Sybase ASE
- [x] remove `windows-2019` image test workflow
- [ ] execute all TFM tests on single db instance to save time on test-runner and db setup for each TFM

PostgreSQL 9 support removal will go in separate PR if approved.

### CODE REVIEW

**Review by viceroypenguin — COMMENTED** [review]
LGTM - not approving since draft

**Comment by viceroypenguin** [comment]
Update CONTRIBUTING.md to remove references to netcoreapp2.1 and related defines

**Comment by MaceWindu** [comment]
Which references? I don't see any left

**Comment by MaceWindu** [comment]
I still need to fix CI testing, but otherwise it is ready for review

**Review by viceroypenguin — APPROVED** [review]

**Review by sdanyliv — APPROVED** [review]

**Review by igor-tkachev — APPROVED** [review]

**Pull request merged**
