### PR TITLE
Fixed regression with BinaryAggregateExpression when working with parameters

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes issue #673

### CODE REVIEW

**Comment by ili** [comment]
No test to reproduce #673?

**Comment by sdanyliv** [comment]
It's something new from @MaceWindu, really reproduced only using his branch. I've not foud simple way to extract test.

**Comment by ili** [comment]
@MaceWindu i'll merge this PR, and it will be great if you'll be able to write unit test later

**Comment by MaceWindu** [comment]
Will do

**Comment by MaceWindu** [comment]
Sorry, looks like there will be no test for it.

When I tried to reproduce it without Merge, I found what caused this issue:  ContextParser.Context.SetParameters method was passing Builder.Expression (with BinaryAggregateExpression) to SetParameters instead of query.Expression. Changing it fixed problem too.

Because this class used only by old and new Merge API and I fixed it - I don't see another way to reproduce it anymore.

Anyway, I think it was a good improvement.

**Comment by ili** [comment]
OK, let it be so )

**Pull request merged**
