### PR TITLE
Fix for #421

### PR DESCRIPTION
**Pull request by ili**

### CODE REVIEW

**Comment by ili** [comment]
@sdanyliv in general we do not need update test. Changes were done with parameters and this code is same. Also i'v done a review of all places where `SqlParameter.IsQueryParameter` is set to `false` and applied changes there. So it should be OK

**Comment by sdanyliv** [comment]
@ili, possible, but when additional changes in code will appear - it sould be good if such testes will fail.

**Comment by ili** [comment]
@sdanyliv additional tests for update are added :)

**Comment by sdanyliv** [comment]
Great ;)

**Pull request merged**
