### PR TITLE
Fix outer apply columns nullability tracking

### LINKED ISSUE #4090: Data mapping fails with nested OUTER APPLY
# Describe your issue

When executing a query containing nested OUTER APPLY, changing the order of the fields requested by the query produces correct or incorrect results.  It appears that the SQL is generated correctly either way, as the logged SQL works correctly in SQL Server either way.

Below you will see that moving `id = purchaseOrder.Id` prior to `returnReason = ...` produces correct results, while vice versa does not.  Also you will see that the produced SQL is identical except for the order of the columns in the SELECT statement, which is correct.

I can write a PR to demonstrate this issue and validate it when fixed.

# Steps to reproduce

## Successful sample

```cs
var query =
    from purchaseInvoice in Db.PurchaseInvoices
    select new {
        id = purchaseInvoice.Id,
        purchaseOrder = (
            from purchaseOrder in Db.PurchaseOrders
            where purchaseOrder.Id == purchaseInvoice.PurchaseOrderId
            select new {
                id = purchaseOrder.Id,
                returnReason = (
                    from returnReason in Db.ReturnReasons
                    where returnReason.Id == purchaseOrder.ReturnReasonId
                    select new {
                        description = returnReason.Description
                    }).FirstOrDefault(),
                notes = purchaseOrder.Notes
            }).FirstOrDefault()
    };
```

### Results (correct)

```json
{
  "id": 1,
  "purchaseOrder": {
    "id": 1,
    "returnReason": null,
    "notes": "Notes 1"
  }
}
```

### SQL generated (correct)

```sql
--  SqlServer.2017 (asynchronously)
DECLARE @take Int -- Int32
SET     @take = 1
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1
DECLARE @take_2 Int -- Int32
SET     @take_2 = 1

SELECT TOP (@take)
	[purchaseInvoice_1].[Id],
	[t2].[id],
	[t2].[returnReason],
	[t2].[notes]
FROM
	[PurchaseInvoice] [purchaseInvoice_1]
		OUTER APPLY (
			SELECT TOP (@take_1)
				[purchaseOrder_1].[Id] as [id],
				[t1].[returnReason],
				[purchaseOrder_1].[Notes] as [notes]
			FROM
				[PurchaseOrder] [purchaseOrder_1]
					OUTER APPLY (
						SELECT TOP (@take_2)
							[returnReason_1].[Description] as [returnReason]
						FROM
							[ReturnReason] [returnReason_1]
						WHERE
							[returnReason_1].[Id] = [purchaseOrder_1].[ReturnReasonId]
					) [t1]
			WHERE
				[purchaseOrder_1].[Id] = [purchaseInvoice_1].[PurchaseOrderId]
		) [t2]
```

## Failed sample

```cs
var query =
    from purchaseInvoice in Db.PurchaseInvoices
    select new {
        id = purchaseInvoice.Id,
        purchaseOrder = (
            from purchaseOrder in Db.PurchaseOrders
            where purchaseOrder.Id == purchaseInvoice.PurchaseOrderId
            select new {
                returnReason = (
                    from returnReason in Db.ReturnReasons
                    where returnReason.Id == purchaseOrder.ReturnReasonId
                    select new {
                        description = returnReason.Description
                    }).FirstOrDefault(),
                id = purchaseOrder.Id, // <--- note this was moved
                notes = purchaseOrder.Notes
            }).FirstOrDefault()
    };
```

### Results (incorrect)

```json
{
  "id": 1,
  "purchaseOrder": null
}
```

### Expected results

```json
{
  "id": 1,
  "purchaseOrder": {
    "returnReason": null,
    "id": 1,
    "notes": "Notes 1"
  }
}
```

### SQL generated (correct)

```sql
--  SqlServer.2017 (asynchronously)
DECLARE @take Int -- Int32
SET     @take = 1
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1
DECLARE @take_2 Int -- Int32
SET     @take_2 = 1

SELECT TOP (@take)
	[purchaseInvoice_1].[Id],
	[t2].[returnReason],
	[t2].[id], -- <-- note this was correctly moved
	[t2].[notes]
FROM
	[PurchaseInvoice] [purchaseInvoice_1]
		OUTER APPLY (
			SELECT TOP (@take_1)
				[t1].[returnReason],
				[purchaseOrder_1].[Id] as [id], -- <-- note this was correctly moved
				[purchaseOrder_1].[Notes] as [notes]
			FROM
				[PurchaseOrder] [purchaseOrder_1]
					OUTER APPLY (
						SELECT TOP (@take_2)
							[returnReason_1].[Description] as [returnReason]
						FROM
							[ReturnReason] [returnReason_1]
						WHERE
							[returnReason_1].[Id] = [purchaseOrder_1].[ReturnReasonId]
					) [t1]
			WHERE
				[purchaseOrder_1].[Id] = [purchaseInvoice_1].[PurchaseOrderId]
		) [t2]
```

### Environment details

`Linq To DB` version: 5.1.1

Database (with version): Azure SQL Managed Instance

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.1.1

Operating system: Windows 10 Pro

.NET Version: .NET 6

### PR DESCRIPTION
**Pull request by Shane32**
Fix #4090 

The queries here were mostly copied from the tests for #3462 and although are not quite the same as in #4090, effectively demonstrate the bug.  Note that only when the nested OUTER APPLY has no data does the bug manifest itself, and only depending on the order of the columns selected.

### CODE REVIEW

**Comment by Shane32** [comment]
image

**Comment by Shane32** [comment]
Not sure exactly what/how it was fixed, but looks good. (I can’t hit approve because I created the PR)

**Comment by MaceWindu** [comment]
outer joins should expose columns to query as nullable, which wasn't done for `outer apply` columns and mapper used wrong column (from nested apply) to detect wether record from top apply exists

**Comment by MaceWindu** [comment]
baselines changes are correct (multiple nested outer apply tests generated incorrect SQL...)

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
@Shane32 from baselines changes for older tests I see that we now generate is_empty column for this case, but I suspect we don't have assert of mapping results, so it makes sense to add another test (or add asserts to existing tests)

**Comment by MaceWindu** [comment]
@Shane32 that's good one. We need to create two is_empty fields but second one got removed as duplicate

**Review by sdanyliv — APPROVED** [review]

**Comment by Shane32** [comment]
Looks great @MaceWindu  !!  Having the baselines makes reviewing PRs like this so much easier 👍 !

**Review by igor-tkachev — APPROVED** [review]

**Pull request merged**
