### PR TITLE
Fix for #708 (BinaryAggregateExpression regression)

### LINKED ISSUE #708: Updating to 1.8.1 causes numerous strange errors (random & reproducible)
After updating to 1.8.1 most of our previously working code is broken. Sometimes it happens only for repetative execution, but other times it happens on first run (NRE).

Before submitting this issue I spent a full day trying out different configurations with 1.8.0 + 1.8.1: executing tests on real SQL Server to exclude any mistakes with SQL CE but the results are the same. (even gone back on code versions to check with older implementation)

**Using 1.8.0 (or older) everything is correct**, but with 1.8.1 unexplainable things happen, like:
 - null value returned where its not possible
 - different value returned than should be in the database
 - data is not saved into the database when it should have been
 - expression eval dies with NRE

The first 3 are completely mysterious and I cannot reproduce or even identify the cause of them. There are no errors, warnings...the query executes without problem, but the result is trash.

For the last one, it happens almost exactly on the same point:
Source\Linq\Query.cs:78 (in `public Expression GetIQueryable(int n, Expression expr)`)
image
```
Exception message: An exception of type 'System.NullReferenceException' occurred in linq2db.dll but was not handled in user code
Stack trace:
lambda_method(Closure , Expression )
LinqToDB.Linq.Query.GetIQueryable(Int32 n, Expression expr) hely: c:\dev\TEMP\linq2db\Source\Linq\Query.cs, sor: 78
lambda_method(Closure , Expression , Object[] )
LinqToDB.Linq.Query`1.SetParameters(Expression expr, Object[] parameters, Int32 idx) hely: c:\dev\TEMP\linq2db\Source\Linq\Query.cs, sor: 422
LinqToDB.Linq.Query`1.SetCommand(IDataContext dataContext, Expression expr, Object[] parameters, Int32 idx, Boolean clearQueryHints) hely: c:\dev\TEMP\linq2db\Source\Linq\Query.cs, sor: 399
LinqToDB.Linq.Query`1.<RunQuery>d__11.MoveNext() hely: c:\dev\TEMP\linq2db\Source\Linq\Query.cs, sor: 379
LinqToDB.Linq.Query`1.<Map>d__69.MoveNext() hely: c:\dev\TEMP\linq2db\Source\Linq\Query.cs, sor: 1184
```

For one example, the original LINQ expression is:
```
.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.Where(
        .Constant<LinqToDB.Linq.Table`1[Entities.Substitution]>(LinqToDB.Linq.Table`1[Entities.Substitution]),
        '(.Lambda #Lambda1<System.Func`2[Entities.Substitution,System.Boolean]>)),
    '(.Lambda #Lambda2<System.Func`2[Entities.Substitution,Entities.User]>))

.Lambda #Lambda1<System.Func`2[Entities.Substitution,System.Boolean]>(Entities.Substitution $substitution)
{
    .Call System.Linq.Queryable.Contains(
        .Constant<DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0>(DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0).subQuery,
        $substitution.Id) && $substitution.StartDate <= System.DateTime.Now && $substitution.EndDate >= System.DateTime.Now
}

.Lambda #Lambda2<System.Func`2[Entities.Substitution,Entities.User]>(Entities.Substitution $substitution)
{
    $substitution.User
}
```
... where `.Constant<DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0>(DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0).subQuery` is:
```
.Call System.Linq.Queryable.Select(
    .Call System.Linq.Queryable.Where(
        .Constant<LinqToDB.Linq.Table`1[.Entities.SubstitutionUser]>(LinqToDB.Linq.Table`1[.Entities.SubstitutionUser]),
        '(.Lambda #Lambda1<System.Func`2[.Entities.SubstitutionUser,System.Boolean]>)),
    '(.Lambda #Lambda2<System.Func`2[.Entities.SubstitutionUser,System.Guid]>))

.Lambda #Lambda1<System.Func`2[.Entities.SubstitutionUser,System.Boolean]>(.Entities.SubstitutionUser $substitutionUsers)
{
    $substitutionUsers.UserId == (.Constant<DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0>(DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0).user).Id
}

.Lambda #Lambda2<System.Func`2[.Entities.SubstitutionUser,System.Guid]>(.Entities.SubstitutionUser $substitutionUsers)
{
    $substitutionUsers.SubstitutionId
}
```
(`(.Constant<DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0>(DataAccess.Implementations.UserRepository+<>c__DisplayClass13_0).user).Id` is a valid Guid value)

Real code:
```c#
var user = GetById(userID);

var subQuery = from substitutionUsers in Context.SubstitutionUsers
               where substitutionUsers.UserId == user.Id
               select substitutionUsers.SubstitutionId;

var query = from substitution in Context.Substitutions
            where subQuery.Contains(substitution.Id) &&
                    substitution.StartDate <= DateTime.Now &&
                    substitution.EndDate >= DateTime.Now
            select substitution.User;

user.SubstitutedUsers = query.ToList();
```

### Steps to reproduce
I will try to corner the cases even more but there is currently nothing to stick to as the linq2db part is running okay but produces invalid results (except the NRE above).

**I would like to ask to make investigation on the diff of 1.8.0<->1.8.1**  

We are stuck on 1.8.0 and would not be able to upgrade ever in the future which is a complete disaster for our long term project. I would be glad if we'd figure out what happened and how to solve it. (will provide any assistance necessary to get over it)

_Extra info_: we are using dynamically compiled classes in some queries. Are there any change on assembly loading/identification in this patch? (to clarify: problems occour even if no dynamic assemblies involved)

### Environment details
linq2db version: *1.8.1*  
Database Server: *SQL Server 2014 SP1* and *SQL Server CE 4.0*  
Database Provider: *SqlServer* and *SqlCe*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.6.2*

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #708.
Optimized building search condition.

### CODE REVIEW

**Comment by detoxhby** [comment]
Feedback: compiled and tested it on previous project (#708) with `UseBinaryAggregateExpression = true;`: almost every test failed with the following error

image

Stack trace:
```
lambda_method(Closure , Expression , Object[] )
LinqToDB.Linq.Query`1.SetParameters(Expression expr, Object[] parameters, Int32 idx) at linq2db\Source\Linq\Query.cs, sor: 422
```

**Comment by sdanyliv** [comment]
@detoxhby, so myx fix do not solves problem?

**Comment by detoxhby** [comment]
@sdanyliv nope

(should change `UseBinaryAggregateExpression` to `true` on this branch for more expressive results from CI)

**Comment by sdanyliv** [comment]
I will

**Comment by sdanyliv** [comment]
@detoxhby, strange. I've tested locally and through CI - nothing criminal.

**Comment by detoxhby** [comment]
@sdanyliv I will provide some tests on next days to help figure this out.

**Comment by detoxhby** [comment]
This is an example expression which causes the reported invalid cast exception:
```c#
value(LinqToDB.Linq.Table`1[Entities.InternalPivotTableGuidEntity]).Where(x => ((x.SETID == Convert(b865e631-57a6-4315-9a78-ad94040e5d5e)) AndAlso (((x.EID1 == Convert(2f5628e3-6e1d-42ad-b43f-48d3ea518431)) AndAlso (x.BETID == Convert(828367ee-7929-4f04-97cb-1bbddd027644))) AndAlso (x.TETID == Convert(null))))).Cast()
```
(+debugView of expression tree)
```
.Call System.Linq.Queryable.Cast(.Call System.Linq.Queryable.Where(
        .Constant<LinqToDB.Linq.Table`1[Entities.InternalPivotTableGuidEntity]>(LinqToDB.Linq.Table`1[Entities.InternalPivotTableGuidEntity]),
        '(.Lambda #Lambda1<System.Func`2[Entities.InternalPivotTableGuidEntity,System.Boolean]>)))

.Lambda #Lambda1<System.Func`2[Entities.InternalPivotTableGuidEntity,System.Boolean]>(Entities.InternalPivotTableGuidEntity $x)
{
    $x.SETID == (System.Guid).Constant<System.Guid>(b865e631-57a6-4315-9a78-ad94040e5d5e) && $x.EID1 == (System.Guid).Constant<System.Guid>(2f5628e3-6e1d-42ad-b43f-48d3ea518431)
    && $x.BETID == (System.Guid).Constant<System.Guid>(828367ee-7929-4f04-97cb-1bbddd027644) && $x.TETID == (System.Nullable`1[System.Guid])null
}
```
The cast is used for base-type recognition (as the actual type is unknown at compile time, but all dynamic type inherits from the base type).

This is as internal query which is constructed dynamically and needs the Convert calls to ensure ValueType/ReferenceType compatbility with every data possible.

Also, please keep in mind that this query works correctly without BinaryAggregate processing.

**Comment by detoxhby** [comment]
**Status**: spent lot of time on some real deep analysis/debugging and ... the problem is somehow related to the `SqlCe` provider as running on `SqlServer` everything is just fine. As I cannot debug into the `parameterAccessor` this could be a bit tricky to determine what is different when running on SQL CE. The thing is, we cannot use `@declare` syntax there and some resolution may causes this problem with the paramteres.

**Comment by detoxhby** [comment]
@ili Alright, I have due this (and next) week for some projects and cannot test it out perfectly.

**Pull request merged**
