### PR TITLE
Updates for SQL Server 2000 testing

### PR DESCRIPTION
**Pull request by Shane32**
This fixes the following issues with testing for SQL Server 2000:
* `sys.sp_addextendedproperty` is named differently in SQL Server 2000 with different parameters.
* `sys.databases` should be accessed via `master.dbo.sysdatabases` and has different columns
* No `SCHEMA_NAME()` function
* `hierarchyid` user-defined type not supported in SQL Server 2000/2005
* User-defined types not supported in SQL Server 2000
* Cannot query `sys.databases` for collation setting (could perhaps query the `sysobjects` table)
* No `xml` data type
* `EXCEPT` not supported
* `INTERSECT` with WHERE clause not supported (it seems)
* Cannot search a binary field
* `OUTER APPLY` not supported

The only behavior change was to the `SqlServer2000SchemaProvider`, which now issues the proper query for the current database's compatibility level.  All other changes were in the tests.

In addition to the above, string concatenation contains a cast to `nvarchar(max)` in certain cases.  SQL Server 2000 does not support `nvarchar(max)` or `varchar(max)`.  I did not fix the tests failing due to that behavior, as it seemed that the behavior should be fixed:
* `Issue1977Tests.Test`
* `Tests.Linq.StringFunctionsTests.ConcatStringsTest`

This has been tested with SQL Server 2000 Standard SP4 running on Windows Server 2008 Standard x86.  Besides the two listed above, all other tests pass.

### CODE REVIEW

**Comment by Shane32** [comment]
Amendment: also `Issue792Tests.TestWithTransactionThrowsFromProvider` fails with SQL Server 2000.  No idea how to fix that error.

**Comment by Shane32** [comment]
`Sql.Strings.cs` has been updated to fix the two other tests relating to string concatenation.

**Comment by Shane32** [comment]
Here's how my tests are configured and what I'm seeing with these updates:
```json
	"NET46": {
		"BasedOn": "LocalConnectionStrings",
		"DefaultConfiguration": "SqlServer.2012",
		"Providers": [
			"SqlServer",
			"SqlServer.2000",
			"SqlServer.2005",
			"SqlServer.2008",
			"SqlServer.2012",
			"SqlServer.2014",
			"SqlServer.2017"
		]
	},

	"CORE21": {
		"BasedOn": "LocalConnectionStrings",
		"DefaultConfiguration": "SqlServer.2012",
		"Providers": [
			"SqlServer",
			"SqlServer.2000",
			"SqlServer.2005",
			"SqlServer.2008",
			"SqlServer.2012",
			"SqlServer.2014",
			"SqlServer.2017"
		]
	}
```
image
With the failed test being:
* `Issue792Tests.TestWithTransactionThrowsFromProvider("SqlServer.2000")`

**Comment by MaceWindu** [comment]
Cool! Thanks to look into it!

**Pull request merged**
