### PR TITLE
Postgres: Quoting of columns like it was in bltoolkit (only the reser…

### PR DESCRIPTION
**Pull request by jogibear9988**
…ved words).

Make SqlBuilder public, so quote Mode can be set !
(Should also not be a static setting) -> more work needed

### CODE REVIEW

**Comment by ili** [comment]
@jogibear9988 really strange logic for me, also i do not understand why not to quote always by default (or quote makes names case sensitive?), but in any way if we are doing quotation configuration available we should make it easy to understand.

For now we do have:
* `None` - we do not use quoting at all (*OK*)
* `Auto` - not used (*???*)
* `Quote` - quote only if any is upper or spaces (*why not all?*)
* `QuoreReserved` - only reserved, but what about spaces?

My suggesting is:
* `None` - we do not use quoting at all 
* `Auto` - quote only if any is upper or spaces (*default as now*)
* `Quote` - quote everything
* `QuoreReserved` - quote only reserved & spaces

**Comment by jogibear9988** [comment]
Yes, quoting makes names case sensitive!

I think your suggestion is good, I will change the Code that it follows your suggestion. (as the class was not yet public, it's a non breaking change if I keep the same default behavior!)

As for now, shoudl I leave the static Variable in the PostgreSQLSqlBuilder or should I add it to the COnfiguration class? (I've already created a Issue to remove the static Configuration Class -> V2)

**Comment by ili** [comment]
I think for now we can leave static field, as done for other providers

**Comment by jogibear9988** [comment]
I've now changed to the following:

- None - we do not use quoting at all (OK)
- Quote - Quote everything
- Needed - Reserved Words & Spaces
- Auto - same as Needed + Uppercase Column Names

**Pull request merged**
