### PR TITLE
Bugfix for #1107

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by sdanyliv** [comment]
I know it is boring, but we need unit tests for that.

**Comment by jogibear9988** [comment]
i‘ll look

**Comment by jogibear9988** [comment]
@sdanyliv I saw, that I accidentally (again) pushed to master instead of my branch ;-(
Should I revert it? (I've added a test for the issue)

**Comment by jogibear9988** [comment]
and one more problem is, the test did not fail on appveyor, but did on my sqlserver db.

maybe it's cause of sqlserver version, or db collation?

**Comment by sdanyliv** [comment]
Let’s fix it here. And merge again. Same branch.
Which exception do you have?

**Comment by jogibear9988** [comment]
it‘s fixed with my changes but without my changes the test does not fail in mssql on appveyor

**Comment by sdanyliv** [comment]
You have to investigate. It can be problem for other users.

**Comment by sdanyliv** [comment]
I’ve missed your previous issue. So everythyng is ok. Thanks.

**Pull request merged**
