### PR TITLE
bugfix for #468

### PR DESCRIPTION
**Pull request by jogibear9988**
converter for enum->string now possible

### CODE REVIEW

**Comment by jogibear9988** [comment]
i will create a unit test for this when #466 is merged

**Comment by jogibear9988** [comment]
do not merge yet, i will do some little changes.

**Comment by jogibear9988** [comment]
I've now added a test! Can be merged

**Comment by ili** [comment]
Planned for today's evening :)

**Comment by jogibear9988** [comment]
looks like some db's could not be reached!

**Comment by ili** [comment]
it looks like i'm a bad boy :( 
i'll fix it

**Comment by jogibear9988** [comment]
;-)

**Pull request merged**
