### PR TITLE
Added scalar support for FromSql method.

### LINKED ISSUE #1769: [PostgreSQL] Implement cross join lateral
Hello.

I'm trying to implement PostgreSQL `cross join lateral` ([pg docs](https://www.postgresql.org/docs/10/queries-table-expressions.html#QUERIES-LATERAL)) and currently have some problems with it.

### Interface
```c#
public static IQueryable<TResult> CrossJoinLateral<TSource, TResult, TLateral>(
	this IQueryable<TSource> source,
	Expression<Func<TSource, TLateral>> lateralSelector,
	Expression<Func<TSource, TLateral, TResult>> resultSelector);

public static IQueryable<TResult> CrossJoinLateral<TSource, TResult, TLateral1, Lateral2>(
	this IQueryable<TSource> source,
	Expression<Func<TSource, TLateral1>> lateralSelector1,
	Expression<Func<TSource, TLateral2>> lateralSelector2,
	Expression<Func<TSource, TLateral1, Lateral2, TResult>> resultSelector);
```

#### `ITable<>.DataContext.FromSql<>`
Failed because `lateralSelector` can not be converted to sql

#### Implement custom `Sql.ExtensionAttribute` with `ChainPrecedence >0`
- It seems the value returned by `GetExpression` is ignored
- Actually cannot select something from lateral in `resultSelector`. This rises `InvalidOperationException` when tries `LinqToDB.SqlQuery.SqlSelectClause.Add(ISqlExpression expr)`

#### `Sql.TableExpressionAttribute`
Actually i got working solution for simple use case but this approach has some disadvantages:
- `TLateral` should be an object
- `IDataContext` is required to create a table so methods should have `ITable<>` instead of `IQueryable<>` in signature
- Workaround with `IDataContext` (get context using reflection):
  * How to convert methods calls in `lateralSelector`?
  * How to find columns names and tables names used in `lateralSelector`?

Could someone give me an advice how i can implement it?

### Motivation
Here few examples uses array `unnest` ([docs](https://www.postgresql.org/docs/10/functions-array.html#ARRAY-FUNCTIONS-TABLE)) and full text search functions [like npgsql for EF](https://www.npgsql.org/efcore/mapping/full-text-search.html#operation-translation) 

#### Simple array `unnest`
```c#
db.GetTable<Foo>()
  .CrossJoinLateral(
      foo => PgArrays.Unnest(foo.Values),
      (foo, lat) => new { foo.Id, lat, })
  .Where(item => item.Id == 1)
  .ToList();
```

Expected SQL:
```sql
select foo.id, lat
from foo, lateral unnest(foo.values) as lat
where foo.id == 1
```

#### Get array values with indexes using `unnest with ordinality` 
```c#
db.GetTable<Foo>()
  .CrossJoinLateral(
      foo => PgArrays.UnnestWithOrdinality(foo.Values),
      (foo, ord) => new { foo.Id, ord.Value, ord.Index, })
  .Where(item => item.Id == 1)
  .ToList();
```

Expected SQL:
```sql
select foo.id, ord.value, ord.index
from foo, lateral unnest(foo.values) with ordinality as ord(value, index)
where foo.id == 1
```

#### More complex example with full text search:
```c#
db.GetTable<Foo>()
  .CrossJoinLateral(
     foo => PgTs.PlainToTsQuery("hello world"),
     foo => PgTs.ToTsVector(foo.First).SetWeight(NpgsqlTsVector.Lexeme.Weight.A.ToString())
                .Concat(
            PgTs.ToTsVector(foo.Second).SetWeight(NpgsqlTsVector.Lexeme.Weight.B.ToString())),
     (foo, query, ts) => new { Foo = foo, Query = query, TextSearch = ts.TextSearch, })
  .Where(item  => item.TextSearch.Matches(item.Query))
  .Select(item => new { item.Foo.Id, Score = PgTs.TsRank(item.TextSearch, item.Query), })
  .OrderBy(result => result.Score)
  .ToList();
```

Expected SQL:
```sql
select foo.id, ts_rank(textsearch, query) score
from foo,
   lateral plainto_tsquery("hello_world") query,
   lateral (
     select setweight(to_tsvector(foo.first ), 'A')
         || setweight(to_tsvector(foo.second), 'B')
   ) ts (textsearch)
where query @@ textsearch
order by score
```

### PR DESCRIPTION
**Pull request by sdanyliv**
Added scalar support for FromSql method.
Added `Sql.AliasExpr()` function to support complex cases when query alias has to be placed before other expression.

Also fixes #1769

### CODE REVIEW

**Comment by MaceWindu** [comment]
@sdanyliv   please check my changes in last commit..

**Comment by sdanyliv** [comment]
Looks good.

**Pull request merged**
