### PR TITLE
Add PostgreSQL 17 support

### LINKED ISSUE #4655: Support DeleteWhenNotMatchedBySourceAnd for Postgres 17
Current [documentation](https://www.postgresql.org/docs/current/sql-merge.html) for Postgres 17 says that MERGE clause supports WHEN NOT MATCHED BY SOURCE [AND] statement,
but DeleteWhenNotMatchedBySourceAnd throws an exception with Postgres provider.

Is there any plan to support this feature?

### LINKED ISSUE #4670: Support MergeWithOutput for postgres 17
I see PG 17 support is coming in vNext, so please ignore this if already done.

When using the following:

`.MergeWithOutputAsync((action, deleted, inserted, source) => inserted.Rowversion2)`

the following SQL is generated:

` (correct sql)
RETURNING
	"NEW".rowversion2`

`Merge Into .... Returning` is a new v17 feature which doesn't support "NEW". It expects the same `returning` syntax that is supported in `select` statements. It looks like it should either be "Target".fieldname or "Source".fieldname based on the currently generated SQL.

Just posting this for visibility. Thanks!

### PR DESCRIPTION
**Pull request by MaceWindu**
- [x] add PGSQL 17 to tests and CI
- [x] remove PGSQL 11-12 from CI (11 is EOL, 12 will be EOL in a month)
- [x] add `NOT MATCHED BY SOURCE` MERGE operations support for PGSQL 17. Fix #4655
- [x] add `RETURNUNG` clause support in MERGE for PGSQL 17. Fix #4670

### CODE REVIEW

**Comment by MaceWindu** [comment]
PG17 also introduce ignore option for bulk copy, but it is a part of not implemented yet feature https://github.com/linq2db/linq2db/issues/4325

**Review by sdanyliv — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
