### PR TITLE
Fluent Mapping -> a defined Property should be included by default

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
If I don't do this, when I use Fluent Mapping, I always have to add another Method after the Property call:

              .Property(e => e.ServerLimitCheckScripts).IsNullable(true)

or 

         .Property(e => e.ServerLimitCheckScripts).IsNullable(true)

when the Property is a complex type!

**Comment by ili** [comment]
@jogibear9988 if you'll provide any test to reproduce the problem, and check the fix, it would be great! :)

**Comment by jogibear9988** [comment]
will do so

**Comment by jogibear9988** [comment]
what is the expected way? that i commit a failing test, then create a fix so that the test works? can we configure appveyor to run the unit tests?

**Comment by ili** [comment]
@jogibear9988 test + fix IMHO is the best way :)

appveyor runs tests now (can see in checks for this PR) :)

**Comment by jogibear9988** [comment]
checks pass, can this be merged?

**Comment by ili** [comment]
I'm going to do it tomorrow.
Now @igor-tkachev is reviewing core support

**Pull request merged**
