### PR TITLE
Issue/2547

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by sdanyliv** [comment]
I will stop pipeline. It is not a fix but avoids others to run tests.

**Comment by jogibear9988** [comment]
Icould not test against a sql server.
Hopfully my tests works and fails

**Comment by jogibear9988** [comment]
@sdanyliv seems the test did work.
do we already have fixed this, or does my test not reproduce the error?

**Comment by sdanyliv** [comment]
@jogibear9988, test is incomplete. I do not see what to fix.

**Comment by jogibear9988** [comment]
closed at the moment, cause it does not reproduce the issue

**Pull request closed without merging**
