### PR TITLE
Possible fix for #498

### PR DESCRIPTION
**Pull request by sdanyliv**
@igor-tkachev, another fix that needs your support.
I have not found any source history, even in BLToolkit, why this part of code was introduced,

In #498 introduced Association with CanBeNull = false. After grouping join become not weak and duplicate is not removed later.

### CODE REVIEW

**Comment by jogibear9988** [comment]
What does the "Weak" Property on a JoinedTable mean?

**Comment by sdanyliv** [comment]
As i suppose this notifies optmizator that if there is no dependencies on this join (projections, etc.) - it can be removed. This technique widely used for Associations.

**Comment by jogibear9988** [comment]
But shouldn't the SQL Code Gen also work is a join is not weak, so #498 should also work without removing this code?

(Does not mean that that code should not be removed if it leads to doubled joins)

**Comment by sdanyliv** [comment]
I don't clearly understand your comment. I've removed small piece of code that makes Weak INNER JOIN to become strong. Why only INNER and why it is introduced ni GroupByBuilder - that's is the question. Looking for the sample that can break my fix.

**Comment by jogibear9988** [comment]
Why does your change make a join strong? You removed code wich sets weak to false!

**Comment by sdanyliv** [comment]
Hm, my change removed weak to strong conversion. That is what i've written in previous comment.

**Comment by jogibear9988** [comment]
seems igor removed the code (commented out), so this is fixed?

**Comment by sdanyliv** [comment]
@ili, i think Igor already committed fix https://github.com/linq2db/linq2db/commit/cb853e67bc1613c3b8493ead2f240d486876f09a

**Pull request merged**
