### PR TITLE
Fix for #3402. Corrected Boolean column expression generation.

### LINKED ISSUE #3402: Empty SQL expression is generated
Hello,

One of our projects is migrating from BLT to Linq2db.
The project has lots of queries that worked in BLT but fail in Linq2db.
Here is an example that sometimes generates an empty SQL expression:

```csharp
var fullAccess = IsFullAccess(); // true or false

var permissions = (
		from ess in db.GetTable<EmployeeScheduleSection>()
		let allowEdit = fullAccess || ess.AdditionalPermissions.Any(y => y.IsActive)
		where allowEdit
		select new
		{
			SectionID = ess.ID,
		}
).ToList();
```

If `fullAccess` is false, the generated query is OK:

```sql
--  SQLite.Classic SQLite
SELECT
	[t1].[ID]
FROM
	(
		SELECT
			CASE
				WHEN EXISTS(
					SELECT
						*
					FROM
						[VEMPLOYEE_SCHDL_SEC_ADDTL_PERM] [y]
					WHERE
						[ess].[ID] = [y].[EMPLOYEE_SCHEDULE_SECTION_ID] AND
						[y].[IS_ACTIVE] = 1
				)
					THEN 1
				ELSE 0
			END as [allowEdit],
			[ess].[ID]
		FROM
			[VEMPLOYEE_SCHEDULE_SECTIONS] [ess]
	) [t1]
WHERE
	[t1].[allowEdit] = 1 AND [t1].[allowEdit] IS NOT NULL
```

If `fullAccess` == true, the generated query is broken:

```sql
--  SQLite.Classic SQLite
SELECT
	[t1].[ID]
FROM
	(
		SELECT
			CASE
				WHEN () THEN 1
				ELSE 0
			END as [allowEdit],
			[ess].[ID]
		FROM
			[VEMPLOYEE_SCHEDULE_SECTIONS] [ess]
	) [t1]
WHERE
	[t1].[allowEdit] = 1 AND [t1].[allowEdit] IS NOT NULL
```

BLToolkit handles both situations fine.

### Environment details
linq2db version: 3.6.0
Database Server: any
Database Provider: any
Operating system: Windows
.NET Framework: 4.8

### Source code

```csharp
namespace Linq2dbErrors.Model
{
	[Table(Name = "VEMPLOYEE_SCHEDULE_SECTIONS")]
	public class EmployeeScheduleSection
	{
		[Column(Name = "ACTIVE", CanBeNull = false)]
		public bool Active { get; set; }

		[Column(Name = "ID", CanBeNull = false, IsPrimaryKey = true)]
		public long ID { get; set; }

		[Column(Name = "NAME", CanBeNull = false)]
		public string Name { get; set; }

		[Association(ThisKey = "ID", OtherKey = "EmployeeScheduleSectionID")]
		public List<EmployeeScheduleSectionAdditionalPermission> AdditionalPermissions { get; set; }
	}

    [Table(Name = "VEMPLOYEE_SCHDL_SEC_ADDTL_PERM")]
	public class EmployeeScheduleSectionAdditionalPermission
	{
		[Column(Name = "EMPLOYEE_SCHEDULE_SECTION_ID", CanBeNull = false, IsPrimaryKey = true)]
		public long EmployeeScheduleSectionID { get; set; }

		[Column(Name = "IS_ACTIVE", CanBeNull = false)]
		public bool IsActive { get; set; }
	}
}

// ----------------------------

namespace Linq2dbErrors
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Creating the in-memory database...");

			DataConnection.TurnTraceSwitchOn();
			DataConnection.OnTrace = traceInfo =>
			{
				if (traceInfo.TraceInfoStep == TraceInfoStep.BeforeExecute)
					Console.WriteLine(traceInfo.SqlText);
			};

			using var db = new DataConnection(ProviderName.SQLite, @"Data Source=:memory:");
			db.CreateTable<EmployeeScheduleSection>();
			db.CreateTable<EmployeeScheduleSectionAdditionalPermission>();

			// no errors:
			var fullAccess = false;

			var permissions = (
				from ess in db.GetTable<EmployeeScheduleSection>()
				let allowEdit = fullAccess || ess.AdditionalPermissions.Any(y => y.IsActive)
				where allowEdit
				select new
				{
					SectionID = ess.ID,
				}
			);

			var sql1 = permissions.ToString();
			var data1 = permissions.ToList();

			// error:
			fullAccess = true;

			permissions = (
				from ess in db.GetTable<EmployeeScheduleSection>()
				let allowEdit = fullAccess || ess.AdditionalPermissions.Any(y => y.IsActive)
				where allowEdit
				select new
				{
					SectionID = ess.ID,
				}
			);

			var sql2 = permissions.ToString();
			var data2 = permissions.ToList(); // throws exception
		}
	}
}
```

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #3402

### CODE REVIEW

**Comment by yallie** [comment]
Thanks a lot for this fix! 🚀

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
