### PR TITLE
Fix for #3186. Improved PostgreSQL Update FROM queries generation.

### LINKED ISSUE #3186: Regression bug in generation Update SQL statement for PostgreSQL
Hi Linq2Db!

We are migrating our project to the latest version of Linq2Db. 
Was found the regression bug.
This relates to the generation Update SQL statement for PostgreSQL database.

The bug was found in versions starting from 3.3.0 (including the current 3.4.3) but not in 3.2.3 or less.

### Steps to reproduce

**SQL test structure** and inserting test data for the test:

```sql

--Creating some 3 test tables

-- services
create table element_services
(
    id                  varchar(100)  not null  constraint pk_el_service  primary key,
    is_process_service  boolean not null default false,
    is_deleted          boolean not null default false
);
-- test data
insert into element_services (id, is_process_service) values ('TestProcessService', true);
insert into element_services (id, is_process_service) values ('TestElementService', false);

-- categories
create table component_categories
(
    id                           varchar(100)  not null  constraint pk_comp_category  primary key,
    service_id                   varchar(100)  not null  constraint fk_comp_category_service references element_services,
    is_deleted                   boolean not null default false
);
--test data
insert into component_categories (id, service_id) values ('TestProcessCategory1', 'TestProcessService');
insert into component_categories (id, service_id) values ('TestProcessCategory2', 'TestProcessService');
insert into component_categories (id, service_id) values ('TestElementCategory1', 'TestElementService');
insert into component_categories (id, service_id) values ('TestElementCategory2', 'TestElementService');

-- components
create table components
(
    id              varchar(100)  not null  constraint pk_comp  primary key,
    category_id     varchar(100)  not null  constraint fk_comp_category references component_categories,
    service_id      varchar(100)  not null  constraint fk_comp_service references element_services,
    is_deleted          boolean not null default false
);
--test data
insert into components (id, category_id, service_id) values ('TestProcessComponent1', 'TestProcessCategory1', 'TestProcessService');
insert into components (id, category_id, service_id) values ('TestProcessComponent2', 'TestProcessCategory2', 'TestProcessService');
insert into components (id, category_id, service_id) values ('TestElementComponent1', 'TestElementCategory1', 'TestElementService');
insert into components (id, category_id, service_id) values ('TestElementComponent2', 'TestElementCategory2', 'TestElementService');

```

**The test C# code:**
```c#
categories = db
	.GetTable<ElementServiceInfo>()
	.Where(ie => ie.Id == "TestProcessService")
	.InnerJoin(db.GetTable<ComponentCategoryInfo>(),
		(sr, ctg) => sr.Id == ctg.ServiceId,
		(sr, ctg) => ctg);

categories.InnerJoin(db.GetTable<ComponentInfo>(),
	(ct, cm) => ct.Id == cm.CategoryId && !cm.IsDeleted,
	(ct, cm) => ct
).Set(r => r.IsDeleted, true).Update();
```

**The output at the moment of updating in version 3.2.3:**

```
25.08.2021 02:14:46.825  BeforeExecute
-- PostgreSQL PostgreSQL.9.5 PostgreSQL
DECLARE @IsDeleted Boolean
SET     @IsDeleted = True

UPDATE
	component_categories
SET
	is_deleted = :IsDeleted
FROM
	element_services ie,
	component_categories ctg,
	components cm
WHERE
	ie.id = 'TestProcessService' AND
	ie.id = ctg.service_id AND
	ctg.id = cm.category_id AND
	cm.is_deleted = False AND
	component_categories.id = ctg.id

DataConnection: ====================================
25.08.2021 02:14:46.839  Query Execution Time (AfterExecute): 00:00:00.0158863. Records Affected: 2.
```
*Records Affected: 2*. **This is expected and correct.**

**The output at the moment of updating in version 3.4.3:**

```
25.08.2021 02:17:33.946  BeforeExecute
-- PostgreSQL PostgreSQL.9.5 PostgreSQL
DECLARE @IsDeleted Boolean
SET     @IsDeleted = True

UPDATE
	component_categories
SET
	is_deleted = :IsDeleted
FROM
	element_services ie
		INNER JOIN component_categories ctg ON ie.id = ctg.service_id
		INNER JOIN components cm ON ctg.id = cm.category_id AND cm.is_deleted = False
WHERE
	ie.id = 'TestProcessService'

DataConnection: ====================================
25.08.2021 02:17:33.959  Query Execution Time (AfterExecute): 00:00:00.0141906. Records Affected: 4.
```
_Records Affected: 4_. **This is not expected and looks wrong.**

Obviously, there is no filter in the SQL statement of new 3.3.0 (3.4.3) version:
**component_categories.id = ctg.id**
Perhaps the filter is being ignored because comparing executes by the same table. But this is wrong because the context of mentioning the table is different.

Thank you for the researching issue and for fixing it in advance!

### Environment details
linq2db version: *3.4.3* / *3.2.3*
Database Server: *PostgreSQL 12.1*
Database Provider: *Npgsql 5.0.7*
Operating system: *Windows 10*
.NET Framework: *.Net Core 3.1*

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #3186

### CODE REVIEW

**Comment by MaceWindu** [comment]
I see from baselines that queries removed some unnecessary brackets. Could it be that #2897 addressed too?

**Comment by sdanyliv** [comment]
Only AND is optimised.

**Review by MaceWindu — APPROVED** [review]
Ok, David Blaine

**Pull request merged**
