### PR TITLE
Update Benchmarks

### PR DESCRIPTION
**Pull request by MaceWindu**
- fix net5.0 support by benchmarks
- disable netcore 2.1/3.1 benchmarks for now
- add concurrent benchmark

### CODE REVIEW

**Comment by MaceWindu** [comment]
Compare master vs refactored concurrent performance:
image
vs
image

**Comment by jogibear9988** [comment]
> Compare master vs refactored concurrent performance:
> 
> **Current**
> image
> 
> **Refactored**
> image

Net5 compiled is slower?

**Comment by MaceWindu** [comment]
Yep

**Comment by jogibear9988** [comment]
Any Idea why? Maybe we should raise an issue somewhere at a MS repo?

**Comment by MaceWindu** [comment]
No idea. We don't have many platform-specific behavior. Maybe events implemented differently under .net 5

**Pull request merged**
