### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
@MaceWindu should I also change CodeOfConduct?

**Comment by MaceWindu** [comment]
Yep, would be nice. Not such an importan information to make it separate section so people's eyes will stumble on it.

**Comment by jogibear9988** [comment]
@MaceWindu okay now?

**Comment by MaceWindu** [comment]
I'm fine with it :-)

**Pull request merged**
