### PR TITLE
Rename all Issue Tests

### PR DESCRIPTION
**Pull request by jogibear9988**
Fix sorting in Visual Studio

### CODE REVIEW

**Comment by jogibear9988** [comment]
Why?

Some Tests already Start with „0“ in Name

**Comment by jogibear9988** [comment]
any more suggestions? I don't like the random order of the classes in VS

**Comment by sdanyliv** [comment]
Actually i’m just afraid of loosing easy way to access history. If no one other has obligations, we can do that. Wait for others and resolve conflicts.

**Comment by jogibear9988** [comment]
closing this. 

as it's not needed, and sq @sdanyliv sais, history access is then harder

**Pull request closed without merging**
