### PR TITLE
Fix for issue #2356

### LINKED ISSUE #2356: Setting of DateTimeKind does not work
We have this code in our backend:

     mappingSchema.SetConvertExpression<DateTime, DateTime>(dt => DateTime.SpecifyKind(dt, DateTimeKind.Utc));

but it does not seem to work.

Don't know if it happend with update to v3 or before. Using Postgres Database

### PR DESCRIPTION
**Pull request by jogibear9988**
Fixes #2356

### CODE REVIEW

**Comment by sdanyliv** [comment]
Test i not relevant to the issue. It is not Postgres.

**Comment by jogibear9988** [comment]
Issue is also present in Sqlserver& Sqlite

**Comment by sdanyliv** [comment]
Which column type do you have in Postgres? It is important!

**Comment by jogibear9988** [comment]
I know that there are some types wich have no timezoneinfo.
Because of that we introduced that converter.

**Comment by sdanyliv** [comment]
Let's check for regressions.

**Comment by jogibear9988** [comment]
is it possible to create a hotfix release with this fix?

**Comment by jogibear9988** [comment]
@sdanyliv & @MaceWindu thanks for finding the issue

**Pull request merged**
