### PR TITLE
Fix Linq2DB with System.Data.Sqlite on Mono

### PR DESCRIPTION
**Pull request by jogibear9988**
a file URI only starts with "file://" the next slash is part of the path!

### CODE REVIEW

**Comment by ili** [comment]
in other [cases](https://github.com/linq2db/linq2db/search?utf8=%E2%9C%93&q=CodeBase.Replace&type=Code) we also do have `file:///`

**Comment by jogibear9988** [comment]
okay, i'll have a look

**Comment by jogibear9988** [comment]
we should fix like here http://stackoverflow.com/a/4107765/579623

**Comment by ili** [comment]
@jogibear9988 i think yes, but there is one problem, for ex we can have a path:
`c:\myfolder\#subfolder`
it would be `file://c:\myfolder\#subfolder` (or smth like that) so `LocalPath` would return only `c:\myfolder\` (evetything beore `#`) because everything after `#` is treated like `Uri.Fragment`

So I'm commonly using this method:
```cs
		public static string GetFileFromUri(this Uri uri)
		{
			if(!uri.Scheme.Equals("file", StringComparison.OrdinalIgnoreCase))
				throw new ArgumentException(string.Format("{0} - is not a file Uri", uri));

			return Path.Combine(uri.PathAndQuery, uri.Fragment);
		}
```

**Comment by jogibear9988** [comment]
Fix should work, don't know why build fails...

**Comment by jogibear9988** [comment]
Can you also merge this?

**Pull request merged**
