### PR TITLE
issues:278

### PR DESCRIPTION
**Pull request by 10der**
GetQuery/FindQuery: bad performance

### CODE REVIEW

**Comment by ili** [comment]
not clear about performance. for now frequently used queries ate on the top of cache list

**Comment by 10der** [comment]
Kk. I'll investigate this issue again.

**Comment by ili** [comment]
Thanks! We are waiting for feedback! :):)

**Comment by ili** [comment]
Gettiing back to this issue, may be we can do like this:

```cs
static Query<T> FindQuery(IDataContextInfo dataContextInfo, Expression expr)
{
	Query<T> prev = null;
	var      n    = 0;

	for (var query = _first; query != null; query = query.Next)
	{
		if (query.Compare(dataContextInfo.ContextID, dataContextInfo.MappingSchema, expr))
		{
			if (prev != null)
			{
				prev.Next  = query.Next;
				query.Next = _first;
				Interlocked.Exchange(_first, query); // HERE!
			}

			return query;
		}

		if (n++ >= CacheSize)
		{
			query.Next = null;
			return null;
		}

		prev = query;
	}

	return null;
}
```

**Comment by MaceWindu** [comment]
closing in favor of #645

**Pull request closed without merging**
