### PR TITLE
Fix for issues 4544

### PR DESCRIPTION
**Pull request by sdanyliv**
Based on https://github.com/linq2db/linq2db/pull/4533, so it is blocked until parent branch is merged.

Fixes regressions from #4540

### CODE REVIEW

**Comment by MaceWindu** [comment]
@sdanyliv rebase?

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
All test runs crashed with StackOverflow :D

**Comment by sdanyliv** [comment]
Changes moved to https://github.com/linq2db/linq2db/pull/4553

**Pull request closed without merging**
