### PR TITLE
Fix compatibility issues with Contained SQL Server databases

### LINKED ISSUE #2922: [Feature][MSSQL] Contained database support
When using

`await entries.IntoTempTableAsync(linq2dbContext);`

in a contained database, SQL server gives an error:

```
User-named PRIMARY KEY constraint `PK_XXX` is not allowed on temp table `#XXX` because it is being created in a contained database. <...>
```
(https://docs.microsoft.com/en-us/sql/relational-databases/databases/modified-features-contained-database?view=sql-server-ver15#temporary-tables - "Named constraints may not be used in temporary tables")

---

Code responsible for generating table names in case of temporary tables in

```
linq2db.dll!LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.GetTablePhysicalName.__GetName|12_0
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.GetPhysicalTableName
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildPhysicalTable
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildStartCreateTableStatement
linq2db.dll!LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.BuildStartCreateTableStatement
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildCreateTableStatement
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql x3
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.GetCommand
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.CreateExecutionQuery
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.SetQuery
linq2db.dll!LinqToDB.Linq.QueryRunnerBase.SetCommand
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync
linq2db.dll!LinqToDB.Linq.QueryRunner.NonQueryQueryAsync
linq2db.dll!LinqToDB.Linq.QueryRunner.SetNonQueryQuery.AnonymousMethod__1
linq2db.dll!LinqToDB.Linq.QueryRunner.CreateTable<T>.QueryAsync
```

handles temporary tables properly by looking at `tableOptions`, while primary key SQL generation in

```
linq2db.dll!LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.BuildCreateTablePrimaryKey
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildCreateTableStatement
linq2db.dll!LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql x3
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.GetCommand
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.CreateExecutionQuery
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.SetQuery
linq2db.dll!LinqToDB.Linq.QueryRunnerBase.SetCommand
linq2db.dll!LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync
linq2db.dll!LinqToDB.Linq.QueryRunner.NonQueryQueryAsync
linq2db.dll!LinqToDB.Linq.QueryRunner.SetNonQueryQuery.AnonymousMethod__1
linq2db.dll!LinqToDB.Linq.QueryRunner.CreateTable<T>.QueryAsync
```

handles it (by letting SQL server to generate primary constraint name which is proper way to create temporary tables in context of contained databases) by looking at primary key name which is generated from table name:

https://github.com/linq2db/linq2db/blob/5d1d815da2179a3e7bb9e8517ffd4a77a128de55/Source/LinqToDB/SqlProvider/BasicSqlBuilder.cs#L1275

As table name is generated from passed T without any #, when passed temporary table name is null

https://github.com/linq2db/linq2db/blob/37d0f108214c2fc0e6f1991c9d08627c605a9241/Source/LinqToDB/SqlQuery/SqlTable.cs#L66

, `BuildCreateTablePrimaryKey` fails to handle temporary tables.

### Steps to reproduce

Do `await entries.IntoTempTableAsync(linq2dbContext);` with a contained database, where `entries` is a list of objects which has a `[Key]` attribute on a property

### Environment details
linq2db version: *v3.3.0*
Database Server: *SQL Server 13*
Database Provider: *SQL Server*
.NET Framework: *.NET Core 3.1*

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #2922

- added new test provider to test in contained db mode
- disabled primary key name generation for sql server temp tables (not other issues found by tests)
- disabled primary key generation for DB2 temp tables (not supported by db)

### CODE REVIEW

**Review by viceroypenguin — APPROVED** [review]

**Comment by MaceWindu** [comment]
`Operand type clash: MAINTENANCE TOKEN is incompatible with VARCHAR`

Just a bug in Sybase.. m'kay

**Comment by MaceWindu** [comment]
Interesting, on older ASE version I use for local testing it still fail but with more sane (but still irrelevant) message
`Function LIKE invoked with wrong number or type of argument(s)`

**Comment by MaceWindu** [comment]
Ok, something wrong with tests fltering, those two tests already marked as tests that kill Sybase and excluded from test run, but still executed.

**Pull request merged**
