### PR TITLE
Add support constant as association key

### PR DESCRIPTION
**Pull request by genusP**
See #753

### CODE REVIEW

**Comment by sdanyliv** [comment]
I think algorithm should support string constants, that may contain spaces and comas.

**Comment by sdanyliv** [comment]
@genusP, don't do anyting according this feature, maybe we have better idea how to implement such functionality in more generic way.

**Comment by genusP** [comment]
Well I'll wait

**Comment by ili** [comment]
We have discussed this issue and more generic way would be:
```cs
[Assosiation(ExpressionPredicate = "ThisOtherPredicate")]
public IEnumerable<OtherClass> Other { get; set; }

static Expression<Func<ThisClass, OtherClass, bool>> ThisOtherPredicate => 
    (t, o) => t.OtherId == o.Id && o.Target == "ThisClass";

```

So I'm closing this PR for now, this would be implemented in 1.9.0.

**Pull request closed without merging**
