### PR TITLE
Array parameter value logging

### LINKED ISSUE #4122: SQL Trace with string array parameter
I'm trying to debug a query that has a string array parameter but trace is not outputting array values just System.String[]

```
trce: LinqToDB[0]
      --  PostgreSQL.9.5 PostgreSQL
      DECLARE @services -2147483629 -- Object
      SET     @services = System.String[]
      DECLARE @take Integer -- Int32
      SET     @take = 1000
``` 
My guess is that ToString was used but I cannot override ToString of an array, and in my case it needs to be an array, not a list.

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #4122

### CODE REVIEW

**Review by igor-tkachev — APPROVED** [review]

**Review by Shane32 — DISMISSED** [review]

**Comment by jods4** [comment]
Bikeshedding: I think the default value of logging 50 values per array is kind of a lot (esp. compared to the current release 0).
I'd rather settle to a lower default such as 8, it's enough to get an idea what's in an array parameter and it has a lower impact.
If someone needs to log a lot of elements the option can be changed manually.

**Comment by viceroypenguin** [comment]
> Bikeshedding: I think the default value of logging 50 values per array is kind of a lot (esp. compared to the current release 0). I'd rather settle to a lower default such as 8, it's enough to get an idea what's in an array parameter and it has a lower impact. If someone needs to log a lot of elements the option can be changed manually.

I agree. This matches behavior in other systems, like xUnit, which show only a portion of the array for descriptive purposes.

**Comment by MaceWindu** [comment]
\azp run test-all

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
