### PR TITLE
test for issue #2854

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by sdanyliv** [comment]
@jogibear9988, how about creating test using DynamicLINQ?

**Comment by jogibear9988** [comment]
I don't think the error has anything to do with dynamic linq.
Dynamic Linq only creates Expressions so why should I need it?
Did my tests not fail? Cause they do on my system

**Comment by sdanyliv** [comment]
It is just good for regression. I assume that validation function has a bug, but why empty string come to this function?

**Comment by jogibear9988** [comment]
but why empty string come to this function? 
??? empty string to wich function? I don't understand....

**Comment by sdanyliv** [comment]
Original issue has call stack: `LinqToDB.DataProvider.Oracle.Oracle11SqlBuilder.IsValidIdentifier`

**Comment by jogibear9988** [comment]
Maybe original issue is an other problem.
I only thougt, after linq2db Update I've also an IndexOutOfRange exception. Maybe could be the same root cause.

**Comment by sdanyliv** [comment]
So, this Is not test for the original issue. And why I'm asking to add DynamicLINQ variant.

**Comment by jogibear9988** [comment]
But I still think dynamic linq is not relevant.
He need to tell what query he'd like to do, so we can create a test for it.

Expressions from c# queries and the ones created from dynamic linq look the same.

**Comment by jogibear9988** [comment]
We use dynamic linq all over our system, and those querys all work also we newest linq2db.
Only this one I posted here fails

**Comment by jogibear9988** [comment]
@sdanyliv should I create an extra issue for my problem?

**Comment by sdanyliv** [comment]
If your issue has another call stack yes. But better create additional DynamicLINQ test here.

**Comment by jogibear9988** [comment]
I've asked the author for his query. Yes mine has an other callstack. I'll create a new issue and move the test

**Pull request closed without merging**
