### PR TITLE
Enable some tests, remove MySql.Data testing against MariaDB

### LINKED ISSUE #2932: PostgreSQL Test Error using Queryable.Any() inside select member data when using Union() / UnionAll()
**model**
```c#
[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull] public int Id { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Table2_Table_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table2> Table2 { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="Table2")]
	public partial class Table2
	{
		[PrimaryKey(1), NotNull] public int Id       { get; set; } // integer
		[PrimaryKey(2), NotNull] public int ParentId { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Table2_Table
		/// </summary>
		[Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table2_Table", BackReferenceName="Table2")]
		public Table Table { get; set; }

		#endregion
	}
```

**works without Union**
```c#

            var query = (from t1 in db.Table
                         select new
                         {
                             t1.Id,
                             Check = t1.Table2.Any()
                         });
            query.ToArray();//works
```

**problem with Union**
```c#
            var query = (from t1 in db.Table
                         select new
                         {
                             t1.Id,
                             Check = t1.Table2.Any()
                         })
                         .UnionAll(from t1 in db.Table
                                   select new
                                   {
                                       t1.Id,
                                       Check = t1.Table2.Any()
                                   });
            query.ToArray();//Error: Npgsql.PostgresException: '42601: subquery must return only one column'
```
Error: Npgsql.PostgresException: '42601: subquery must return only one 

**temporary fix**
```c#
            var query = (from t1 in db.Table
                         select new
                         {
                             t1.Id,
                             Check = t1.Table2.Any() ? true : false
                         })
                         .UnionAll(from t1 in db.Table
                                   select new
                                   {
                                       t1.Id,
                                       Check = t1.Table2.Any() ? true : false
                                   });
            query.ToArray();//works
```

query tested with empty row data
### Environment details
linq2db version: 3.3.0
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

### PR DESCRIPTION
**Pull request by MaceWindu**
- working test for #2932 (fix #2932)
- enable now working test for dynamic query from https://stackoverflow.com/questions/61081571
- enable fulljoin test for SQLite as it supports it since 3.39.0
- some updated to local setup scripts
- unpin tested mariadb version

### CODE REVIEW

**Comment by MaceWindu** [comment]
Oracle refused to support recent mariadb changes, which makes MySql.Data unusable with MariaDB, so we officially drop support of MySql.Data for MariaDB

https://bugs.mysql.com/bug.php?id=109331

**Comment by MaceWindu** [comment]
Good riddance TBH

**Review by viceroypenguin — APPROVED** [review]

**Review by igor-tkachev — APPROVED** [review]

**Pull request merged**
