### PR TITLE
Add passing and skipped failing tests for issues 2895, 3160, 3161

### PR DESCRIPTION
**Pull request by Shane32**
See:
- #2895 
- #3160 
- #3161

### CODE REVIEW

**Comment by Shane32** [comment]
Note: the test for #2895 was copied verbatim from PR #3021

**Comment by Shane32** [comment]
Note that two tests for #3160 produce incorrect SQL due to #3161 but pass because the nested cross apply only returns a single column.  Notes were added to the baseline PR linked here.  Once #3161 is fixed, we should see (a) the tests still pass, and (b) the SQL is cleaned up in the baselines.

**Review by sdanyliv — APPROVED** [review]

**Comment by Shane32** [comment]
@MaceWindu I cannot merge the baseline PR.  Can you do so?

**Comment by MaceWindu** [comment]
you should have permissions now

**Comment by Shane32** [comment]
Thanks!

**Comment by Shane32** [comment]
I can't yet.... even after signing out and signing into GitHub.  Still says I don't have write access to the repo.

> **This pull request is still a work in progress**
> Only those with write access to this repository can mark a draft pull request as ready for review.

**Comment by MaceWindu** [comment]
Should work now

**Pull request merged**
