### PR TITLE
Fix issues with enumerable merge source reuse

### LINKED ISSUE #2377: Linq2db 3.0.1 Merge operations do not update internal cache
With the 3.0.1 release there is an issue, where cached values are not updated when using multiple merge operations in a row. Not only that, but the actual values in the database are not updated aswell, since subsequent merge queries are using cached sql for the operation. The easy workaround I've used in the affected project (used linq2db 2.9.7 previously) right now is to clear caches before running a merge operation, but this is not something I am happy with.

Sadly I did not have enought time yet to test it with the 3.0.0.

### Steps to reproduce

Here is a code sample with a simple setup to reproduce the case

```c#
[Table]
public class Test
{
	[Column(IsPrimaryKey = true)]
	public long Id { get; set; }
	[Column]
	public Guid SomeField1 { get; set; }
	[Column]
	public DateTime? SomeField2 { get; set; }
	[Column]
	public decimal? SomeField3 { get; set; }
}

// ... initialize connection settings, etc.

// initialize a collection to merge
var testItems = new[]
{
	new Test
	{
		Id = 1,
		SomeField1 = Guid.NewGuid(),
		SomeField2 = DateTime.Now,
		SomeField3 = decimal.Zero
	},
	// ...
};

using var db = new DataConnection(settingsBuilder.Build());

// Insert data with merge
await db.GetTable<Test>()
	.Merge()
	.Using(testItems)
	.OnTargetKey()
	.UpdateWhenMatched()
	.InsertWhenNotMatched()
	.MergeAsync();

// read values from Test 
var queryResult = await db.GetTable<Test>()
	.FirstOrDefaultAsync(x => x.Id == 1);
// expected output queryResult.SomeField3 = 0
// actual output queryResult.SomeField3 = 0

// update testItems e.g. set new value to one of the fields.
testItems[0].SomeField3 = 2313 
// or even add a new element to the list, it wouldn't be saved to the db anyway

// Update data with merge
await db.GetTable<Test>()
	.Merge()
	.Using(testItems)
	.OnTargetKey()
	.UpdateWhenMatched()
	.InsertWhenNotMatched()
	.MergeAsync();

// read values from Test 
var queryResult = await db.GetTable<Test>()
	.FirstOrDefaultAsync(x => x.Id == 1);
// expected output queryResult.SomeField3 = 2313
// actual output queryResult.SomeField3 = 0

// Regular Update works just fine
await db.UpdateAsync(testItems[0]);

var queryResult = await c.GetTable<Test>()
	.FirstOrDefaultAsync(x => x.Id == 1);
// expected output queryResult.SomeField3 = 2313
// actual output queryResult.SomeField3 = 2313
```

### Environment details
linq2db version: *3.0.1*
Database Server: *MsSQL2017*
Database Provider: *Microsoft.Data.SqlClient*
Operating system: *Win10*
.NET Framework: *.net core 3.0*

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #2377

Issue caused by conversion of enumerable source to set of values during query parsing, which makes it not reusable.
Moved values parsing to query execution phase.
Issue not present in v2, because we never cached merge in v2.

While it fix issue, I'm not happy with `EnumerableContext` code...

### CODE REVIEW

**Comment by viceroypenguin** [comment]
If I ever get brave enough to touch using enumerable source anywhere, I'll fix `EnumerableContext` properly. If...

**Comment by MaceWindu** [comment]
Marking as draft as it should be retested after #2347 merged

**Pull request merged**
