### PR TITLE
Added Completed trace steps, issue #3010.

### LINKED ISSUE #3010: TraceInfoStep.Completed is not always triggered
Most database operations go through steps like BeforeExecute → AfterExecute → Completed (or Error). That's very convenient because it allows to gather statistics along the way and then log it once per query.

For ExecuteReader we can measure query execution (the time between BeforeExecute and AfterExecute) and data fetching (between AfterExecute and Completed) separately. That's so cool.

Unfortunately, some queries don't trigger the **Completed** step. Examples:

| Query example | TraceInfo steps triggered |
| --------------|---------------------------|
| db.GetTable&lt;MyTable&gt;().ToArray(); | BeforeExecute, AfterExecute, Completed |
| db.SetCommand("select * from MyTable").Query&lt;MyTable&gt;().ToArray(); | BeforeExecute, AfterExecute |
| db.GetTable&lt;MyTable&gt;().Count(); | BeforeExecute, AfterExecute, Completed |
| db.SetCommand("select count(*) from MyTable").Execute&lt;int&gt;(); | BeforeExecute, AfterExecute |
| db.GetTable&lt;MyTable&gt;().Set(t => t.Name, t => t.Name).Update(); | BeforeExecute, AfterExecute, Completed |
| db.SetCommand("update MyTable set Name = Name").Execute(); | BeforeExecute, AfterExecute |

Can we make this behavior consistent and trigger the **Completed** step for all successful queries?

### PR DESCRIPTION
**Pull request by yallie**
Fix #3010.

Not sure if I put them in the right place though.

### CODE REVIEW

**Review by MaceWindu — APPROVED** [review]

**Comment by MaceWindu** [comment]
Thanks!

**Comment by yallie** [comment]
Thanks for cleaning it up! 👍

**Pull request merged**
