### PR TITLE
Revert "Fix for #2895. More aggressive eager loading detection. (#3021)"

### PR DESCRIPTION
**Pull request by Shane32**
This reverts commit 8fa97de6a45225e70de98979c5d69fede0973ae4.

The reason for the reversion is the regressions listed in #3160 .  A separate PR will be issued to add tests to ensure the regression does not reassert itself, possibly along with minor fixes.

### CODE REVIEW

**Comment by MaceWindu** [comment]
What about #2895? At least we shouldn't revert tests (just disable them if they still fail without fix)

**Comment by Shane32** [comment]
I can certainly add a disabled copy of the other test to my subsequent PR. I figured for cleanliness it would be best if this PR was exactly a revert of the other PR. I’m open to suggestions.

**Comment by Shane32** [comment]
@sdanyliv What's the next step here?

**Pull request merged**
