### PR TITLE
Release 2.6.0

### PR DESCRIPTION
**Pull request by MaceWindu**
Tests:
- [x] T4 tests
- [x] Core 1
- [x] Core 2
- [x] NETFX
- [x] [core2, netfx] FromSqlTests.TestTableValueFunction test
- ~[ ] [netfx] DB2.TestInsertOrUpdate test~ false alarm

@linq2db/testers guys, we are ready to push new release tomorrow with a lot of cool features. Would be nice if you can provide some feedback.

Release notes: https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap

@RoyC-Retail-Assist could you prepare new iSeries release this week (if needed, we can help) so we can release linqpad integration during weekend?

### CODE REVIEW

**Comment by RoyC-Retail-Assist** [comment]
I'll do it on Friday assuming that I don't hit any regression issues.

**Comment by detoxhby** [comment]
I won't be able to run the full test suite until friday

**Comment by RoyC-Retail-Assist** [comment]
@MaceWindu do you know when you are likley to release this?  I can sort out a new iSeries provider package today but don't know when i will be able to do it over the weekend if the release isn't ready.

**Comment by MaceWindu** [comment]
I think we will release in 2 hours, if https://github.com/linq2db/linq2db/pull/1467 will fix last remaining issue

**Comment by MaceWindu** [comment]
Ok, all tests passed. Just need to wait for AppVeyor to finish

**Comment by MaceWindu** [comment]
@RoyC-Retail-Assist release should appear on nuget in 10-15 minutes

**Comment by RoyC-Retail-Assist** [comment]
@MaceWindu - I've hit the first problem....

I'm overriding DynamicDataProviderBase.SetParameter method but this has disappeared.  Can you suggest what the correct override should be to achieve the same outcome?

I tried just removing the override to see if anything else has broken and I'm getting issues with underscores being passed through as table aliases.  The iSeries insists on table names and aliases starting with an alpha character and I know I did something to fix this but cannot remember or find where.

Just to make things worse, I'm having random issues in connecting to our iSeries at the moment which I'm hoping that a reboot of my pc will fix.  It's making life hard when trying to debug the failing tests though.

**Comment by MaceWindu** [comment]
@RoyC-Retail-Assist 
Please check list of changes to existing API: https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#breaking-changes

SetParameter didn't disappeared but just changed type of parameter

**Comment by sdanyliv** [comment]
@RoyC-Retail-Assist, we know about breaking changes: see [release notes](https://github.com/linq2db/linq2db/wiki/Releases-and-Roadmap#breaking-changes)

We changed in functions `SetParameter` and `SetParameterType` parameter `dataType` from `DataType` -> `DbDataType`
```cs
public override void SetParameter(IDbDataParameter parameter, string name, DbDataType dataType, object value)

protected override void SetParameterType(IDbDataParameter parameter, DbDataType dataType)

```
How to work with this new type you can found in other Data Providers.

To correct aliases write the following code in your `Finalize()` method of optimizer:
```cs
		public override SqlStatement Finalize(SqlStatement statement)
		{
			new QueryVisitor().Visit(statement, expr =>
			{
				switch (expr.ElementType)
				{
					case QueryElementType.SqlParameter:
						{
							var p = (SqlParameter)expr;
							p.Name = p.Name?.TrimStart('_');
							break;
						}
					case QueryElementType.TableSource:
						{
							var table = (SqlTableSource)expr;
							table.Alias = table.Alias?.TrimStart('_');
							break;
						}
					case QueryElementType.Column:
						{
							var column = (SqlColumn)expr;
							column.RawAlias = column.RawAlias?.TrimStart('_');
							break;
						}
				}
			});

			return base.Finalize(statement);
		}

```

**Comment by RoyC-Retail-Assist** [comment]
@sdanyliv  Oops I should have read the release notes.  I'll let you know if I hit any other issues.

**Comment by RoyC-Retail-Assist** [comment]
Ok I've converted the SetParameter method.  Your DB2 implementation of this was nearly what I needed.

I've tried to add the code to change the aliases but RawAlias is internal so I can't set it.

**Comment by sdanyliv** [comment]
Ok, try to use `column.Alias`

**Comment by RoyC-Retail-Assist** [comment]
@sdanyliv I've made a bit of progress but I'm hitting problems with my unit tests.  I'm not sure if it is my test project that is giving the issues or something that has changed elsewhere.

On some tests the ConnectionString Data Source, User and Password are being replaced with what look to be placeholders Data Source={ISERIES}; Persist Security Info=True;User ID={USERNAME};Password={PASSWORD};Library List=LINQ2DB;Default Collection=LINQ2DB;Naming=1;  

For other tests the connection string is correct.

Any ideas on where to look to resolve this?

**Comment by sdanyliv** [comment]
Everything in `TestBase`, also check https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/blob/master/Tests/DataProviders.json

**Comment by RoyC-Retail-Assist** [comment]
OK I'm a muppet.  I have four "provider" to test against in UserDataProviders.json but, to speed things up I removed three of them but forgot to set the DefaultConfiguration to the one I had kept.

I'm down to only 3 tests failing but will have to pick this up again sometime tomorrow.  I'm hoping that I can get things sorted by sometime on Sunday but might have a few more dumb questions for you.

**Comment by RoyC-Retail-Assist** [comment]
I've just published v2.6.0 of the package and it should be available in 15 minutes or so.  The friendly aliases caused me a bit of a problem where our iSeries wouldn't accept the test with Russian(?) characters.  I've put in a workaround to use the "old" style table aliases if the alias contains any non-Latin character set characters.  Good work on the new features and your help.

**Comment by MaceWindu** [comment]
Great! I will update linqpad integration asap: https://github.com/linq2db/linq2db.LINQPad/pull/19

**Comment by MaceWindu** [comment]
@RoyC-Retail-Assist , BTW, does iAccess register DbFactoryProvider? Maybe you can add support for it in next version like that (new feature in 2.6):
https://github.com/linq2db/linq2db/commit/16f7f48621e509bcb5740be0c418c8ff295122df#diff-9a9660de95e9bb1460460f81c173657b
It will allow us to remove specific version of IBM.Data.DB2.iSeries.dll from distribution

**Comment by RoyC-Retail-Assist** [comment]
I haven't made any changes apart from those required by breaking changes.  If you raise an issue for this I'll look into it when I get time (probably over Christmas).

**Comment by sdanyliv** [comment]
> The friendly aliases caused me a bit of a problem where our iSeries wouldn't accept the test with Russian(?) 

My fault, we have to skip friendly aliases when they contain non-english characters. Will prepare fix for this.

**Comment by RoyC-Retail-Assist** [comment]
Thanks.  My workaround is a bit of a hack but it allowed me to get the package published.  It is a part of the same issue I had with the undercores as aliases.

Once you have this done I'll remove my hack and sort the DBProviderFactory in the same release.

**Pull request merged**
