### PR TITLE
Fix for Issue #569 (CROSS JOIN)

### PR DESCRIPTION
**Pull request by sdanyliv**
Added support for CROSS JOIN #569

### CODE REVIEW

**Comment by jogibear9988** [comment]
@ili merge?

**Comment by ili** [comment]
I need to tests for all databases before merging, i'll try to do it on next few days...

**Comment by jogibear9988** [comment]
aren't or unit tests on appveyor against all databases?

**Comment by ili** [comment]
no, only Access, SqlCe, SQLite, NorthwindSqlite, MySql57, PostgreSQL, SqlServer.2012

**Comment by ili** [comment]
Moved to #591

**Pull request closed without merging**
