### PR TITLE
improve types reveng for mysql

### LINKED ISSUE #2313: T4 model converts unsigned tinyint(3) in a sbyte
T4 model converts unsigned tinyint(3) in a sbyte (using .NET5.0)

### Steps to reproduce

database table
```sql
CREATE TABLE `inverterLogs` (
	`tStamp` DATETIME NOT NULL DEFAULT current_timestamp(),
	`idInverter` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
	`data` TINYBLOB NOT NULL DEFAULT '0',
	`operatingMode` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`faultCodeH` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`faultCodeL` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0'
)
COMMENT=''
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

conversion result
```c#
[Table("inverterLogs")]
public partial class InverterLog
{
	[Column("tStamp"),        NotNull] public DateTime TStamp        { get; set; } // datetime
	/// <summary>
	/// id inverter di riferimento
	/// </summary>
	[Column("idInverter"),    NotNull] public sbyte    IdInverter    { get; set; } // tinyint(3) unsigned
	[Column("data"),          NotNull] public byte[]   Data          { get; set; } // tinyblob
	[Column("operatingMode"), NotNull] public sbyte    OperatingMode { get; set; } // tinyint(3) unsigned
	[Column("faultCodeH"),    NotNull] public sbyte    FaultCodeH    { get; set; } // tinyint(3) unsigned
	[Column("faultCodeL"),    NotNull] public sbyte    FaultCodeL    { get; set; } // tinyint(3) unsigned
}
```

### Environment details
linq2db version: v3.0.0-rc.1
Database Server: 10.3.21-MariaDB
Database Provider: MySqlConnector  v3.0.0-rc.1
Operating system: w10 1903
.NET Framework: .NET5.0

### PR DESCRIPTION
**Pull request by MaceWindu**
Fixes #2313

### CODE REVIEW

**Comment by Shane32** [comment]
Perhaps this is a bit off topic, but is there any support for `DateTimeOffset` for the `timestamp` field?  Should there be?  I looked up some MySQL docs and it seems that `timestamp` is always stored in UTC, converted to local time (or possibly a specified time zone) upon access.  This seems important.  If nothing else, perhaps the `DateTime` should have the `DateTimeKind` property set properly.  Perhaps this happens already.  Just thinking out loud here...

**Comment by MaceWindu** [comment]
You can use DateTimeOffset with MySqlConnector (we have tests) for this field in linq2db, but MySql.Data cannot handle DateTimeOffset (produce some strange error). Could be fixed by converting DTO to DT on data exchange between linq2db and provider probably.

**Pull request merged**
