### PR TITLE
New Fix for #475 and Test

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
Hopefully the test works, could not run it on my machine

**Comment by ili** [comment]
@jogibear9988 still not clear for me...
if we are using `Single` there should be only one row in result dataset. So using `Take(1).Single()` looks like a hack, why not to use `First()` if we are not sure about rows count and do not care about it?

**Comment by ili** [comment]
Yap, I see "if it works for linq2objects it should for linq2db" :):)

**Comment by jogibear9988** [comment]
thats what i mean!

**Comment by jogibear9988** [comment]
I don't say that it's agood idea to write it so. but it's correct code, and should return the same result as linq2objects!

**Pull request merged**
