### PR TITLE
better logging for sqlserver bulk copy

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by sdanyliv** [comment]
@jogibear9988, do not merge yet. Let others to decide.

**Comment by jogibear9988** [comment]
Why what= Why let others decide, or why this change?

**Comment by jogibear9988** [comment]
Why my change? Because i've errors in the Mapping ("caseing") but it worked without BulkCopy. Now if I have an error, I see the Column Names tried

**Comment by igor-tkachev** [comment]
I like the idea to provide more details. The question is why lambda?

**Comment by jogibear9988** [comment]
cause i thought to build the string obly when logging is enabled (micro perf. optimation)

**Pull request merged**
