### PR TITLE
Implemented supporting arrays in linq queries

### LINKED ISSUE #957: no way to unpivot data with linqtodb?
Hi Guys,
Love linqtodb, however I've come across an issue that I'd like to see if you have a workaround for.

I need to unpivot data, ie
```cs
var qnames =
  from person in People
  from name in
    new[] { person.Name1 }
    .Concat(new[] { person.Name2 })
  select name;

var names = qnames.ToList();
```
this ends up with an exception: LinqToDB.Linq.LinqException: ''<>h__TransparentIdentifier0.person.FirstName1' cannot be converted to SQL.'

This however works OK on EF 6.

I have tried using an artificial single row table, it dodnt work either. 
```cs
var qnames =
  from person in People
  from name in
    SingleRow.Select(_ => person.Name1)
    .Concat(SingleRow.Select(_ => person.Name2))
  select name;
```
Is there any way to unpivot data with linq2db?

Thanks

### PR DESCRIPTION
**Pull request by sdanyliv**
Implemented CROSS APPLY join based on array. 
Also array can be used as source for queries.

Fix #957

### CODE REVIEW

**Comment by sdanyliv** [comment]
@igor-tkachev, i know that you have done some extra work according this issue. Can you push changes if they are ready. Thanks.

**Comment by sdanyliv** [comment]
Yes some tests should work only for providers that supports CROSS APPLY syntax.

**Comment by MaceWindu** [comment]
And some existing tests started to fail like SelectMany tests

**Comment by sdanyliv** [comment]
Will check, thanks.

**Pull request merged**
