### PR TITLE
test for issue #3823

### PR DESCRIPTION
**Pull request by jogibear9988**
#3823

### CODE REVIEW

**Comment by MaceWindu** [comment]
@jogibear9988 tests doesn't show any issue

**Comment by jogibear9988** [comment]
Try the test in Net7 in Visual Studio. Only when you start in debugger.

**Comment by MaceWindu** [comment]
How is it linq2db concern?

**Comment by jogibear9988** [comment]
I created this test before I knew it is a .Net7 issue. We could close, or merge cause the Test works.

**Comment by MaceWindu** [comment]
let's wait till 7.0.1 release

**Pull request closed without merging**
