### PR TITLE
Test for issue #82

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
It seems that test is only crashing for NorthwindSqlite, but I could not see if it was also ran against "Northwind". So maybe it's only a sqlite error, maybe also one we could not solve? maybe no support from the DB Engine?

**Comment by ili** [comment]
"Northwind" configuration does not run on CI i think we should configure it for Appveyor

**Comment by jogibear9988** [comment]
Does Northwind Database exist in AppVeyor? (don't think so). Are there anywhere import Scripts for Northwind?

**Comment by jogibear9988** [comment]
should I create a import from the sql script from here: https://northwinddatabase.codeplex.com/releases/view/71634 ?

**Comment by jogibear9988** [comment]
@ili @sdanyliv I've now added Northwind from https://northwinddatabase.codeplex.com, but as you see, it's not only a sqlite problem. query does also not work on mssql

do anyone of you know how to fix the freetext errors?

**Comment by ili** [comment]
Moved to #610

**Pull request closed without merging**
