### PR TITLE
[SQL Server] Remove COALESCE "optimization"

### PR DESCRIPTION
**Pull request by MaceWindu**

### CODE REVIEW

**Comment by viceroypenguin** [comment]
Why remove this optimization? In all versions of Sql Server, `IIF()` is more performant than `Coalesce()`.

**Comment by viceroypenguin** [comment]
> Why remove this optimization? In all versions of Sql Server, `IIF()` is more performant than `Coalesce()`.

Sorry, `ISNULL()`, not `IIF()`. NVM.

**Review by viceroypenguin — APPROVED** [review]

**Review by sdanyliv — APPROVED** [review]

**Comment by MaceWindu** [comment]
We should add ISNULL optimization for complex parameters (now or later). E.g. see `SelectTests.Coalesce4`

**Pull request merged**
