### PR TITLE
Chores PR for next release

### PR DESCRIPTION
**Pull request by MaceWindu**
Lot of small fry here which doesn't deserve own PR.

- Update dependencies:
  - [Microsoft.AspNet.OData](https://www.nuget.org/packages/Microsoft.AspNet.OData): 7.5.2 -> 7.5.5
  - [Microsoft.Data.SQLite](https://www.nuget.org/packages/Microsoft.Data.SQLite): 5.0.1 -> 5.0.2
  - [Microsoft.Extensions.DependencyInjection](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection): 3.1.10 -> 3.1.11
  - ~[MySql.Data](https://www.nuget.org/packages/MySql.Data): -> 8.0.21 -> 8.0.23~ still [borken](https://bugs.mysql.com/bug.php?id=101252)
  - [Npgsql](https://www.nuget.org/packages/Npgsql): 4.1.7 -> 4.1.8, 5.0.1.1 -> 5.0.3
  - [NUnit](https://www.nuget.org/packages/NUnit): 3.12.0 -> 3.13.1
  - [Oracle.ManagedDataAccess](https://www.nuget.org/packages/Oracle.ManagedDataAccess): 19.10.0 -> 19.10.1
  - [Oracle.ManagedDataAccess.Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core): 2.19.100 -> 2.19.101
  - [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core): 1.0.113.6 -> 1.0.113.7
  - [IBM.Data.DB2.Core](https://www.nuget.org/packages/IBM.Data.DB2.Core): 3.1.0.300 -> 3.1.0.400
  - [IBM.Data.DB2.Core-lnx](https://www.nuget.org/packages/IBM.Data.DB2.Core-lnx): 3.1.0.300 -> 3.1.0.400
- cherry-pick various fixes from #2728
  - add missing DROP statement in postgresql test script
  - add missing `await` and `ConfigureAwait` calls
  - use `IAsyncDisposable` instead of `IDisposable` in several data reader async flows
  - add `IAsyncDisposable` implementation to `DataReaderAsync`
  - don't run native bulk copy for temp table for Sybase ASE
  - removed unused `QueryRunner.GetParameterAccessor` method
  - add new flags to `SqlProviderFlags` `Equals`/`GetHashCode` implementation
  - don't add another @ to parameter name in `SqlParameter.ToString`, if parameter name already starts with @
- add link to [linq2db PostGIS extensions](https://github.com/apdevelop/linq2db-postgis-extensions) library to readme
- setup .NETAnalyzers and fixed issues from several diagnostics:
  - [CA1018](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1018) : `Mark attributes with AttributeUsageAttribute`
  - [CA1200](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1200) : `Avoid using cref tags with a prefix`
  - [CA1507](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507) : `Use nameof in place of string`
  - [CA1725](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1725) : `Parameter names should match base declaration`
  - [CA1805](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1805) : `Do not initialize unnecessarily`
  - [CA1825](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825) : `Avoid zero-length array allocations`
  - [CA1826](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826) : `Use property instead of Linq Enumerable method`
  - [CA1827](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1827) : `Do not use Count/LongCount when Any can be used`
  - [CA1829](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829) : `Use Length/Count property instead of Enumerable.Count method`
  - [CA1830](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1830) : `Prefer strongly-typed Append and Insert method overloads on StringBuilder`
  - [CA1834](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834) : `Use StringBuilder.Append(char) for single character strings`
  - [CA1836](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1836) : `Prefer IsEmpty over Count when available`
  - [CA2007](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007) : `Do not directly await a Task` (enabled in source projects only, as it is useless and noisy in tests)
  - [CA2012](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2012) : `Use ValueTasks correctly`
  - [CA2016](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2016) : `Forward the CancellationToken parameter to methods that take one`
  - [CA2101](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2101) : `Specify marshaling for P/Invoke string arguments`
  - [CA2201](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201) : `Do not raise reserved exception types`
  - [CA2208](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208) : `Instantiate argument exceptions correctly`
  - [CA2215](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2215) : `Dispose methods should call base class dispose`
  - [CA3075](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca3075) : `Insecure DTD Processing`
  - ~analyzers disabled by default (see `linq2db.Default.props`) and will be run only for `Release` and `Azure` builds as they slow down build process significantly~ enabled, as we found and disabled slow analyzer
  - all analyzers produce error by default (if specific diagnostic not configured) to detect new diagnostics in future (if they produce errors)
- removed source files exclusion from project and replaced it with #if directives
- removed remaining compatibility types for unsupported frameworks
- removed internal duplicate `AsAsyncEnumerable` extension
- address remaining code-review comments from test runner PR
- added link to `good first issue`-labeled issues to readme.md
- added `2019` as recognized version to `SqlServerFactory` (now recognized using v2017 dialect instead of v2008 default dialect)
- fix nullable annotations for result of `FirstOrDefaultAsync`/`SingleOrDefaultAsync` methods
- add `net46` target to `linq2db.Tools` nuget
- bump copyright year `2020` -> `2021`
- fix some `IDEXXXX` suggestions
  - [IDE001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0001): `Simplify name`
  - [IDE002](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0002): `Simplify member access`
  - [IDE003](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0003-ide0009): `Remove this or Me qualification`
  - [IDE004](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0004): `Remove unnecessary cast`
  - [IDE005](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0005): `Remove unnecessary import`

### CODE REVIEW

**Comment by MaceWindu** [comment]
Analyzers enabling task will continue later. Right now it takes a lot of time which we don't have (probably due to our huge `Expressions` dictionary or visitor methods) so I'm going to rise this issue in roslyn repo.

**Comment by MaceWindu** [comment]
wow, looks like roslyn team have some low hanging fruits:
```
  Total analyzer execution time: 135.190 seconds.
  NOTE: Elapsed time may be less than analyzer execution time because analyzers can run concurrently.
  Time (s)    %   Analyzer
  131.483   97   Microsoft.CodeAnalysis.CSharp.NetAnalyzers, Version=5.0.3.2303, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  130.474   96      Microsoft.NetFramework.CSharp.Analyzers.CSharpDoNotUseInsecureXSLTScriptExecutionAnalyzer

```

**Comment by MaceWindu** [comment]
Ok, with this diagnostic disabled, there is no big difference in build time with and without analyzers, so I will enable them for debug build too.

**Comment by viceroypenguin** [comment]
wow... that one analyzer. I'll definitely pay attention to that, I've been trying to turn on analyzers in my other projects and wondering why they were slowing down.

**Review by viceroypenguin — APPROVED** [review]
I've been looking at each one as they come in, no real comments. LGTM

**Review by sdanyliv — APPROVED** [review]

**Pull request merged**
