### PR TITLE
Support for custom expression postprocessing

### PR DESCRIPTION
**Pull request by n9**
This small change adds support for a custom expression postprocessor. (Postprocessor is not configured statically but by particular DataContext.)

### CODE REVIEW

**Comment by n9** [comment]
It looks like that C# 7 is not yet supported.

**Comment by sdanyliv** [comment]
@n9, for which purpose this was introduced?

**Comment by n9** [comment]
Expression postprocessing is useful in case you need tweak the expression before is translated into the native query language (e.g. SQL): for instance, processing application specific annotations.

**Comment by sdanyliv** [comment]
I more looks like preprocessing before parsing. BTW, please correct syntax, we currently supports only C# 6.
For me it's ok, we will check.

**Comment by igor-tkachev** [comment]
```c#
public interface IExpressionPostprocessor
{
	Expression PostprocessExpression(Expression expression);
}
```

???

**Comment by n9** [comment]
@igor-tkachev I have updated the API according to your suggestion.
@sdanyliv I have changed the code to C# 6. And set the lang version in csproj to 6.

**Comment by n9** [comment]
Is this PR ok? Or should I change it somehow?

**Comment by sdanyliv** [comment]
We will merge this PR soon.

**Pull request merged**
