### PR TITLE
Optimizing INNER JOIN

### PR DESCRIPTION
**Pull request by sdanyliv**
Main discussion is here
http://rsdn.ru/forum/prj.rfd/6345934

Removing duplicate inner joins based on table's primary keys

### CODE REVIEW

**Comment by sdanyliv** [comment]
Hi Igor,
Any updates with this pull request? Maybe i have to correct or rewrite something?

**Comment by igor-tkachev** [comment]
I tried to merge it but some tests failed. I will look into it bit later.

**Comment by sdanyliv** [comment]
@ili could you please look at this pull request?
Thanks

**Comment by ili** [comment]
@sdanyliv I'll try my best :)

**Comment by ili** [comment]
@sdanyliv it looks like the situation is: joins are removed, but aliases can be used in another query parts, for ex:
```sql
select j1.Field1, j2.Field2
from t1
inner join JoinTable j1 on t1.Key = j1.Key
inner join JoinTable j1 on t1.Key = j2.Key
where j2.Field3 = 12121
```
would be optimized to
```sql
select j1.Field1, j2.Field2
from t1
inner join JoinTable j1 on t1.Key = j1.Key
where j2.Field3 = 12121
```
and `j2` would become unknown alias

**Comment by sdanyliv** [comment]
I see, currenly i'm on vacation, so i'll try to fix that on monday.

**Comment by ili** [comment]
@sdanyliv that would be great!

**Comment by sdanyliv** [comment]
Hi, @ili, finally i'm here. Can you please send me failing linq query as you described before?
I can not reproduce bug.

**Comment by ili** [comment]
SelectManyTests Basic10 and Basic11

**Comment by ili** [comment]
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Linq/SelectManyTests.cs#L124

**Comment by sdanyliv** [comment]
Found bug, it's belong to my function FlattenInnerJoins. I have to figure out how to handle such situations or maybe correct algorithm to handle duplicates without flattening.
It needs some time, thanks to pointing me to the bug.

**Comment by ili** [comment]
@sdanyliv good ) waiting for PR update :)

**Comment by ili** [comment]
@sdanyliv why closed?

**Comment by ili** [comment]
@sdanyliv I see, new is open :)

**Comment by sdanyliv** [comment]
@ili, opened new one. Tired to fight with git and it's conflicts. I need some practice with it.

**Pull request closed without merging**
