### PR TITLE
FIx ValueConverter support for RemoteContext

### PR DESCRIPTION
**Pull request by MaceWindu**
Fixed incorrect data read using remote context for columns with ValueConverter applied. Discovered when tried to reproduce #3830

### CODE REVIEW

**Comment by MaceWindu** [comment]
Compared to linked issue I'm getting exception, because `bool?` handling is even more broken
```
System.ArgumentException
  HResult=0x80070057
  Message=Argument must be boolean (Parameter 'test')
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse, Type type)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
```

**Review by sdanyliv — APPROVED** [review]

**Review by viceroypenguin — APPROVED** [review]

**Pull request merged**
