### PR TITLE
Add SourceLink support

### LINKED ISSUE #1217: Enable Sourcelink
https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#why-source-link

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #1217

### CODE REVIEW

**Comment by jogibear9988** [comment]
Any Idea why it does not work for net core?

**Comment by jogibear9988** [comment]
Maybe PrivateAssets="All" is needed? see: https://github.com/dotnet/sourcelink

**Comment by jogibear9988** [comment]
Note that .NET Core SDK 2.1.300 or newer is required for SourceLink to work. If building via desktop msbuild (as opposed to dotnet build) you'll need version 15.7.

**Comment by MaceWindu** [comment]
Ok, as I suspected, it is due to some strange caching issues with nuget, when you use same package version for testing. I will fix travis build and merge this commit to test it once more with myget packages to check that appveyor tooling produce binaries with sourcelink support

**Comment by MaceWindu** [comment]
Looks like travis have this issue: https://github.com/travis-ci/travis-ci/issues/9877
but because we don't publish with travis, we just need to disable sourcelink for it

**Pull request merged**
