### PR TITLE
Fix for #2238. Added possibility to create more flexible queryable associations.

### LINKED ISSUE #2238: Pass additional parameters to Association Expression
I have tried to setup `Association` with additional parameters. Similar to how it is done for `ExpressionMethod`:
https://github.com/linq2db/linq2db/blob/9f00cbecbaadc36b5e165dda4a3ae654d6e3756d/Tests/Linq/Linq/ExpressionsTests.cs#L135-L146

I am getting exception that `Expression` must only contain 3 parameters:
https://github.com/linq2db/linq2db/blob/9f00cbecbaadc36b5e165dda4a3ae654d6e3756d/Source/LinqToDB/Mapping/AssociationDescriptor.cs#L294-L297

Can you add support for passing additional parameters? It would simplify calling repeated custom joins.
```
Exception message:
Invalid predicate expression in UserGroup.UsersWithLanguageExpression. Expected: Expression<Func<UserGroup, IDataContext, IQueryable<User>>>
Stack trace:
  at LinqToDB.Mapping.AssociationDescriptor.GetQueryMethod(Type parentType, Type objectType)
  at LinqToDB.Linq.Builder.AssociationHelper.<>c__DisplayClass0_1.<CreateAssociationQueryLambda>b__0(MemberInfo mi)
  at LinqToDB.Linq.Query.AddQueryableMemberAccessors(MemberInfo memberInfo, Func`2 qe)
  at LinqToDB.Linq.Builder.ExpressionBuilder.AddQueryableMemberAccessors(MemberInfo memberInfo, Func`2 qe)
  at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, MemberInfo onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
  at LinqToDB.Linq.Builder.AssociationHelper.BuildAssociationSelectMany(ExpressionBuilder builder, BuildInfo buildInfo, TableContext tableContext, MemberInfo onMember, AssociationDescriptor descriptor, Boolean& isOuter)
  at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
  at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
  at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
  at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap)
  at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSqlExpression(IBuildContext context, Expression expression)
  at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSql(IBuildContext context, Expression expression, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
  at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
  at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
  at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
  at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
  at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
  at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
  at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
  at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
  at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
```

### Steps to reproduce
A simplified version to describe the problem. I have included both `OneToOne` and `OneToMany` relationship examples.

```c#
[TestFixture]
public class Issue : TestBase
{
	public class UserGroup
	{
		[Column]
		public int Id { get; set; }

		[Association(QueryExpressionMethod = nameof(UsersWithLanguageExpression), Relationship = Relationship.OneToMany)]
		public IQueryable<User> UsersWithLanguage(IDataContext db, int languageId)
		{
			return (_usersWithLanguageExpression = _usersWithLanguageExpression ?? UsersWithLanguageExpression().Compile())(this, db, languageId);
		}
		
		public static Expression<Func<UserGroup, IDataContext, int, IQueryable<User>>> UsersWithLanguageExpression()
		{
			return (p, db, languageId) => db
				.GetTable<User>()
				.Where(x => x.UserGroupId == p.Id && x.LanguageId == languageId);
		}
		
		private static Func<UserGroup, IDataContext, int, IQueryable<User>> _usersWithLanguageExpression;
		
		
		[Association(QueryExpressionMethod = nameof(FirstUserWithLanguageExpression), Relationship = Relationship.OneToOne, CanBeNull = true)]
		public User FirstUsersWithLanguage(IDataContext db, int languageId)
		{
			return (_firstUserWithLanguageExpression = _firstUserWithLanguageExpression ?? FirstUserWithLanguageExpression().Compile())(this, db, languageId).FirstOrDefault();
		}
		
		public static Expression<Func<UserGroup, IDataContext, int, IQueryable<User>>> FirstUserWithLanguageExpression()
		{
			return (p, db, languageId) => db
				.GetTable<User>()
				.Where(x => x.UserGroupId == p.Id && x.LanguageId == languageId)
				.Take(1);
		}
		
		private static Func<UserGroup, IDataContext, int, IQueryable<User>> _firstUserWithLanguageExpression;
	}
	
	public class User
	{
		[Column]
		public int Id { get; set; }
		
		[Column]
		public int UserGroupId { get; set; }
		
		[Column]
		public int LanguageId { get; set; }
		
		[Association(ThisKey = nameof(LanguageId), OtherKey = nameof(Issue3.Language.Id), Relationship = Relationship.OneToOne, CanBeNull = true)]
		public Language Language { get; set; }
	}
	
	public class Language
	{
		[Column]
		public int Id { get; set; }
		
		[Column]
		public string Name { get; set; }
	}

	[Test]
	public void TestOneToOneAssociation([IncludeDataSources(TestProvName.AllSqlServer)] string context)
	{
		using (var db = new TestDataConnection(context))
		using (db.CreateLocalTable(new[]
		{
			new UserGroup {Id = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new User {Id = 1, UserGroupId = 1, LanguageId = 1},
			new User {Id = 2, UserGroupId = 1, LanguageId = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new Language {Id = 1, Name = "English"},
			new Language {Id = 2, Name = "French"}
		}))
		{
			var data = db
				.GetTable<UserGroup>()
				.Select(x => new
				{
					x.Id,
					FirstUserId = x.FirstUsersWithLanguage(db, 1).Id,
					LanguageName = x.FirstUsersWithLanguage(db, 1).Language.Name
				})
				.First();

			Assert.AreEqual(1, data.FirstUserId);
			Assert.AreEqual("English", data.LanguageName);
		}
	}
	
	[Test]
	public void TestOneToManyAssociation([IncludeDataSources(TestProvName.AllSqlServer)] string context)
	{
		using (var db = new TestDataConnection(context))
		using (db.CreateLocalTable(new[]
		{
			new UserGroup {Id = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new User {Id = 1, UserGroupId = 1, LanguageId = 1},
			new User {Id = 2, UserGroupId = 1, LanguageId = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new Language {Id = 1, Name = "English"},
			new Language {Id = 2, Name = "French"}
		}))
		{
			var data = db
				.GetTable<UserGroup>()
				.Select(x => new
				{
					x.Id,
					EnglishUserCount = x.UsersWithLanguage(db, 1).Count(),
					FrenchhUserCount = x.UsersWithLanguage(db, 2).Count()
				})
				.First();

			Assert.AreEqual(2, data.EnglishUserCount);
			Assert.AreEqual(0, data.FrenchhUserCount);
		}
	}
}
```

### Environment details
linq2db version: 3.0.0-preview2
Database Server: SQL Server
Database Provider: SqlServer
Operating system: Windows 10
.NET Framework: 4.6.2

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #2238 

@Feroks, please create more use cases in tests to cover more situations.

### CODE REVIEW

**Comment by Feroks** [comment]
Thank you for the fast response. I have added 3 additional tests:
- Chain Associations method calls.
- Transform parameter passed into Association. I have used `string.Replace` as an example.
- Pass multiple parameters to Association method.

This pretty much covers my use cases. Here is a [patch gist](https://gist.github.com/Feroks/c5a9f4c405b134fd9f7fb77b62f83c96).

**Comment by MaceWindu** [comment]
Fix merged by #2239

**Pull request closed without merging**
