### PR TITLE
DataReader reporting TraceInfoStep.Completed step

### PR DESCRIPTION
**Pull request by yallie**
Issue #1355.

Added tracing to the DataReader wrapper's Dispose method.
Looks like the project didn't have any tests related to the tracing, so I've added a fixture.

### CODE REVIEW

**Comment by yallie** [comment]
@sdanyliv Thanks for approving my patch!
Anything else I can do to help merging this PR?

**Comment by jogibear9988** [comment]
The DateTime Type and Now Value should stay?

**Comment by jogibear9988** [comment]
It could also produce wrong results when dailight saveing switch happens between the call

**Comment by MaceWindu** [comment]
Hmm, right. Makes sense to calculate duration more safely.

**Comment by MaceWindu** [comment]
PRs are welcome :)

**Comment by MaceWindu** [comment]
#1367

**Pull request merged**
