### PR TITLE
Add net6.0 to the l2db nuspec

### PR DESCRIPTION
**Pull request by viceroypenguin**

### CODE REVIEW

**Comment by MaceWindu** [comment]
fck

**Review by MaceWindu — APPROVED** [review]

**Comment by MaceWindu** [comment]
I need to verify other projects too. E.g. I see linq2db.aspnet also builds for net6 but not included into nuget. Don't remember when net6 introduced here, probably we should remove it

**Comment by viceroypenguin** [comment]
linq2db.aspnet added net6.0 in #3366 with the other projects. however, I don't see any specific need for it other than possibly referencing a newer version of base libraries.

**Comment by MaceWindu** [comment]
Ah, right `add net6.0 build target to source projects (just for NRT validation on build, no nuget deployment yet)`, so we are fine

**Pull request merged**
