### PR TITLE
oracle persists empty strings as nulls, so to make searches predictab…

### PR DESCRIPTION
**Pull request by gusev-p**
…le we convert empty strings to nulls for search predicates

### CODE REVIEW

**Comment by ili** [comment]
I'v run your test without `OracleSqlBuilder` changes, so it fails for empty string value.
Not sure why should we treat `""` as `null`? why not to use `string.IsNullOrEmpty()`?

**Comment by gusev-p** [comment]
Because for Oracle checking for equality with empty string in searches is useless in any case, it will always return false and is a true sign of a bug.

**Comment by gusev-p** [comment]
It's unnatural and easy to forget to use string.IsNullOrEmpty, especially if app code always explicitly pass empty strings.

**Comment by sdanyliv** [comment]
@ili, maybe it can be configurable on connection/global level?

**Comment by gusev-p** [comment]
Our most painfull scenario is protecting against duplicates by some string key property:
* receive some object with string key from the outside
* select() with filter by equality on this property
* if nothing returned, save this object to db, return selected otherwise

Without this path the code above create duplicates when key property is empty.

**Comment by ili** [comment]
I'll look forward what can we do...

**Pull request merged**
