### PR TITLE
Extended readme with more details about mapping and transaction scope

### PR DESCRIPTION
**Pull request by Usaga**
Extended readme with more details about mapping and transaction scope

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3163) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3163) before we can accept your contribution.<br/><br/>:x: Usaga [sign now](https://cla.dotnetfoundation.org/linq2db/linq2db?pullRequest=3163)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/linq2db/linq2db?pullRequest=3163) it.</sub>

**Review by MaceWindu — CHANGES_REQUESTED** [review]
I'm not sure it is correct to use `Code First` here. While we provide table creation API, we don't have database creation logic and it doesn't have anything with fluent mapping.

**Comment by Usaga** [comment]
I am not sure I understood you right. Fluent Mapping is another way configuring mapping. More flexible. Why you think it related to database creation? We used fluent in our project for configuriong. I is working.

**Comment by MaceWindu** [comment]
Yes, but you mention it as `Fluent configuration (also known as Code First)`.

I had an impression that `code first` term is about creating database from model, but after looking around it looks like one of those buzz-words where everybody has own understanding what it means....

**Review by MaceWindu — APPROVED** [review]

**Comment by MaceWindu** [comment]
I would preferer to not use vague terms, but if microsoft use it in ef.core docs, we probably could expect people to understand it in MS way :)

**Comment by Usaga** [comment]
So, I need to replace all "Code First" to "Fluent"?

**Comment by MaceWindu** [comment]
@sdanyliv what you think? I would prefer to avoid `code first` term in this context

**Comment by sdanyliv** [comment]
Code First usually meaning that database is created from code. Better do not use this term with linq2db.

**Comment by jogibear9988** [comment]
also here: https://entityframeworkcore.com/approach-code-first

If you have used Entity Framework in the past, you will probably have heard about the Code First approach.

Code First workflow begins with classes that describe the conceptual model and then Entity Framework generate a database from that model automatically.

**Comment by jogibear9988** [comment]
Microsoft also calls it "Fluent API"
https://docs.microsoft.com/en-us/ef/core/modeling/

**Pull request closed without merging**
