### PR TITLE
Improve Task.Run()/CancellationToken code

### PR DESCRIPTION
**Pull request by viceroypenguin**
Part of #4475

### CODE REVIEW

**Review by MaceWindu — CHANGES_REQUESTED** [review]
I see code still assume Provider could be not IQueryProviderAsync. Remove it here or you plan to submit another PR?

**Comment by MaceWindu** [comment]
If there is no `IQueryProviderAsync`, then it is not linq2db query provider and calling it with Linq2db API will result in error from provider, in this case `System.Linq.EnumerableExecutor`:
```
System.InvalidOperationException: 'There is no method 'Delete' on type 'LinqToDB.LinqExtensions' that matches the specified arguments'
```

Instead of trying to execute broken code we can throw exception with descriptive message that linq2db API used over non-linq2db query.

PS: if there are valid cases I'm not aware of - we could preserve it

**Comment by viceroypenguin** [comment]
@MaceWindu fair enough - let's do a sep PR for that.

**Review by MaceWindu — APPROVED** [review]

**Pull request merged**
